/**
 * Explicit businesses column allowlists for client-side reads.
 * NEVER include twilio_subaccount_auth_token or other server-only secrets.
 */

/** Billing page - subscription display only. */
export const BUSINESS_SELECT_BILLING =
  'id, name, subscription_started_at, refund_eligible_until, subscription_status, subscription_tier, subscription_monthly_price, monthly_price, trial_start, trial_end, subscription_access_until, past_due_at'

/** Main settings page - profile / costing / reviews / bank. No Twilio secrets. */
export const BUSINESS_SELECT_SETTINGS = [
  'id',
  'name',
  'primary_trade_slug',
  'logo_url',
  'brand_color',
  'brand_text_color',
  'abn',
  'licence_number',
  'address',
  'phone',
  'email',
  'website',
  'payment_threshold',
  'callout_fee_enabled',
  'callout_fee_amount',
  'gst_registered',
  'terms_and_conditions',
  'google_review_link',
  'review_template',
  'gmb_review_link',
  'review_request_email_subject',
  'review_request_sms_template',
  'review_page_title',
  'review_page_message',
  'review_auto_send',
  'bank_bsb',
  'bank_account',
  'bank_name',
  'milestone_require_approval',
  'milestone_approval_hours',
  'milestone_default_split',
  'default_labour_rate',
  'default_admin_rate',
  'track_job_costing',
  'materials_markup_default',
  'timezone',
  'arrival_tracking_enabled',
  'push_notifications_enabled',
].join(', ')

/** Quote/invoice builders - profile, GST, terms, bank. Same secret-exclusion as settings. */
export const BUSINESS_SELECT_DOCUMENTS = BUSINESS_SELECT_SETTINGS

/** Social module context - connection *ids/names* and compose prefs. Never tokens. */
export const BUSINESS_SELECT_SOCIAL = [
  'id',
  'name',
  'phone',
  'website',
  'logo_url',
  'brand_color',
  'brand_text_color',
  'ai_agent_services',
  'facebook_page_id',
  'facebook_page_name',
  'instagram_account_id',
  'instagram_username',
  'gmb_account_id',
  'gmb_location_id',
  'gmb_location_name',
  'tiktok_open_id',
  'tiktok_display_name',
  'tiktok_avatar_url',
  'social_brand_voice',
  'social_default_cta',
  'social_default_platforms',
  'social_overlay_style',
  'social_auto_prompt',
  'social_text_styles',
  'social_logo_corner',
  'social_compose_last_category',
  'social_compose_last_subtype',
].join(', ')

/** AI agent settings - agent config + brand for preview. No Twilio secrets. */
export const BUSINESS_SELECT_AI_AGENT = [
  'id',
  'name',
  'logo_url',
  'brand_color',
  'brand_text_color',
  'ai_agent_enabled',
  'ai_agent_greeting',
  'ai_agent_tone',
  'ai_agent_services',
  'ai_agent_pricing_notes',
  'ai_agent_call_flow_instructions',
  'ai_agent_business_hours',
  'ai_agent_mode',
  'ai_widget_placement',
  'ai_agent_max_call_minutes',
  'ai_agent_silence_timeout_seconds',
  'ai_agent_max_concurrent_sessions',
  'ai_agent_recording_notice',
  'ai_booking_enabled',
  'ai_booking_hours',
  'ai_widget_position',
  'ai_widget_icon_style',
  'ai_widget_custom_icon_url',
  'ai_widget_bubble_color',
  'ai_widget_text_color',
  'ai_backchanneling_enabled',
  'ai_response_speed',
  'ai_interruption_sensitivity',
  'ai_noise_cancellation_mode',
  'ai_idle_reminder_enabled',
  'ai_speech_normalization_enabled',
  'ai_boosted_keywords',
  'ai_voice_id',
  'ai_voice_label',
  'ai_voice_speed',
  'ai_voice_cloning_enabled',
  'ai_voice_is_cloned',
  'ai_cloned_voice_id',
  'ai_cloned_voice_status',
].join(', ')
