import { Rocket } from 'lucide-react'
import type { HelpFaqCategory, HelpFaqQuestion } from '@/components/marketing/help/helpContent'

export const GETTING_STARTED_HELP_CATEGORY_ID = 'getting-started'

export function gettingStartedHelpArticleHref(questionId: string): string {
  return `/help?article=${GETTING_STARTED_HELP_CATEGORY_ID}-${questionId}`
}

const QUESTIONS: readonly HelpFaqQuestion[] = [
  {
    id: 'after-signup',
    q: 'What happens after I sign up?',
    group: 'Start here',
    keywords: ['first login', 'after signup', 'how quickly', 'setup guide', 'onboarding'],
    a: 'If you created the owner account:\n1. Confirm your email.\n2. You land on the welcome setup (onboarding wizard).\n3. Finish it, or use Skip - go to dashboard on the last step. Either way, that first setup is marked complete.\n4. You go to the dashboard. If you still need to choose a plan, StitchedUp opens Billing next. Paid access starts after checkout - there is no product trial that starts when you finish the wizard.\n5. The Setup Guide stays in the sidebar. It is a longer checklist. Finishing the wizard does not finish the Guide.\n\nInvited teammates, VAs, and accountants skip the wizard. They join the business and go to their usual home (dashboard, or Accounts for an accountant).\n\nSee also: What is the onboarding wizard? and What is the Setup Guide?',
  },
  {
    id: 'required-optional',
    q: 'What is required vs optional?',
    group: 'Start here',
    keywords: ['required', 'optional', 'recommended'],
    a: 'Three different meanings of “required”:\n\nRequired to use the account (owner):\n- confirmed email and signup\n- welcome setup finished or skipped (so you can leave those first screens)\n- an active paid plan when Billing asks for one\n\nRequired for a specific feature:\n- an active StitchedUp business number for inbound phone answering and most SMS\n- Stripe connected and active for card payments / Payment Protection\n- the teammate must accept their invite before they can log in\n- Live switched on (plus a number) before the AI answers the phone\n\nOptional / recommended:\n- Google Calendar, Google Business Profile, Social, team, reviews, website leads\n- bank details for transfer invoices (needed to print BSB on invoices, not to open the app)\n- Missed Call AI, Accounts, and PWA install - useful, not part of the first welcome screens\n\nThe Setup Guide marks two items as must-do for the Guide itself: business profile and logo. You can still use jobs and quotes if those Guide items are open.',
  },
  {
    id: 'what-is-stitchedup',
    q: 'What is StitchedUp?',
    group: 'Start here',
    keywords: ['what is', 'platform'],
    a: 'StitchedUp is an all-in-one platform for Australian tradies: leads and CRM, quotes, jobs and calendar, invoices and payments, phone and SMS, AI Receptionist and Missed Call AI, Social, reviews, reporting, Accounts, and team access.\n\nThis Getting Started section is the first-week path. Detailed how-tos live under Phone & SMS, AI Receptionist, Missed Call AI, Team, Social, Accounts, and Billing.',
  },
  {
    id: 'who-is-it-for',
    q: 'Who is StitchedUp for?',
    group: 'Start here',
    keywords: ['tradie', 'office admin', 'va', 'accountant'],
    a: 'StitchedUp is for trade businesses that want leads, quoting, jobs, invoicing, and comms in one place. It works for owner-operators and small teams - field staff, office admins, VAs, managers, and (when available) an accountant login for the books.',
  },
  {
    id: 'onboarding',
    q: 'What is the onboarding wizard?',
    group: 'Onboarding',
    keywords: ['onboarding', 'wizard', '7 steps', 'welcome setup'],
    a: 'The welcome setup is seven screens for a new owner. It is initial setup only - not the full Setup Guide.\n\n1. Business basics - name and phone (needed to continue)\n2. Your trade (needed to continue)\n3. Logo (optional)\n4. Brand color (optional)\n5. ABN and licence (optional)\n6. Payments - a card-protection recommendation amount, not your BSB (needed to continue; default is $1,000)\n7. Google review link (optional)\n\nSaved answers stay on the business. If you refresh, you start at screen 1 again with those answers filled in.\n\nTeam, VA, accountant, and some limited-access signups do not see this wizard.',
  },
  {
    id: 'skip-onboarding',
    q: 'Can I skip onboarding?',
    group: 'Onboarding',
    keywords: ['skip onboarding', 'skip - go to dashboard'],
    a: 'Yes for optional screens (logo, colour, credentials, reviews): use Skip for now.\n\nOn the last screen, Skip - go to dashboard still finishes the welcome setup. You can leave those first screens. It does not mean the business is fully configured, and it does not complete the Setup Guide.\n\nYou still need a paid plan when Billing asks for one.',
  },
  {
    id: 'help-billing-gate',
    q: 'Why can’t I open Help or Billing yet?',
    group: 'Onboarding',
    keywords: ['help', 'billing', 'blocked', 'cannot open'],
    a: 'While you are still on the first welcome setup, Help and Billing are not available yet. Finish or skip that setup, then they open.\n\nSettings and the Setup Guide stay available so you can add a logo, connect Stripe, or connect calendars before you finish the wizard.\n\nIf Billing still opens after you finish, you need to choose a plan - that is separate from the wizard.',
  },
  {
    id: 'reopen-onboarding',
    q: 'Can I reopen onboarding?',
    group: 'Onboarding',
    keywords: ['reopen', 'resume setup'],
    a: 'No. Once the welcome setup is finished or skipped, those screens do not come back.\n\nChange the same details later in Settings. Use the Setup Guide in the sidebar for the remaining checklist.',
  },
  {
    id: 'setup-guide',
    q: 'What is the Setup Guide?',
    group: 'Setup Guide',
    keywords: ['setup guide', 'checklist', 'banner'],
    a: 'The Setup Guide is a live checklist for the business - not one person’s private to-do list.\n\nFind it:\n- Sidebar → Setup Guide\n- Dashboard card (owners usually see this first)\n- A banner on other pages while items remain\n\nA task turns complete when the matching record exists (logo uploaded, quote sent, Stripe active, and so on). There is no generic Mark done.\n\nFinishing the welcome wizard is not the same as finishing the Guide. The Guide stays after onboarding. When every remaining task is done, the banner and dashboard card hide. The page itself stays in the sidebar.\n\nAccountants do not get the Setup Guide.',
  },
  {
    id: 'task-completion',
    q: 'How does a Setup Guide task complete?',
    group: 'Setup Guide',
    keywords: ['task completion', 'mark done', 'auto'],
    a: 'Do the work in the product. The Guide re-reads your account and ticks the task.\n\nYou cannot tap Mark done. You can skip most tasks (not business profile, not logo). Skip does not set the feature up. You can un-skip later.\n\nExamples:\n- First quote completes when a quote is sent (or later). A draft does not count.\n- Card payments completes when Stripe is active, not merely started.\n- Push needs the setting on and this device subscribed.',
  },
  {
    id: 'task-open',
    q: 'Why is a Setup Guide task still open?',
    group: 'Setup Guide',
    keywords: ['still open', 'not complete', 'stuck'],
    a: 'Common reasons:\n- Business profile - name, ABN, address, phone, and timezone all need to be filled. The wizard does not collect address.\n- Logo - skipped on welcome setup, or only a colour was set. The Guide currently ticks this from the logo file, even though the label also mentions brand colour.\n- First quote - still a draft.\n- Card payments - Stripe is not active yet.\n- AI receptionist - tested or in progress, but not fully set up / published.\n- Phone - no active StitchedUp business number yet.\n- Push - toggled on, but this phone or browser is not subscribed.\n\nOpen the task from the Guide. It takes you to the right Settings or page.',
  },
  {
    id: 'skip-task',
    q: 'How do I skip or un-skip a Setup Guide task?',
    group: 'Setup Guide',
    keywords: ['skip task', 'un-skip', 'skippable'],
    a: 'On the Setup Guide page, skippable tasks have Skip. Business profile and logo cannot be skipped.\n\nSkipped items stay on the list so you can Un-skip. Skipping only hides the task from the progress count. It does not turn the feature on.',
  },
  {
    id: 'business-profile',
    q: 'How do I finish my business profile?',
    group: 'Core business setup',
    keywords: ['business profile', 'abn', 'address', 'timezone'],
    a: 'Go to Settings → Business Profile.\n\nFor the Setup Guide to tick this item, fill:\n- business name\n- ABN\n- address\n- phone\n- timezone\n\nThe welcome wizard only required name and phone. Add ABN and address here if you skipped them.',
  },
  {
    id: 'branding',
    q: 'How do I add my logo and brand?',
    group: 'Core business setup',
    keywords: ['logo', 'brand color', 'branding'],
    a: 'Upload a logo and set your brand colour under Settings → Business Profile (Social also has extra logo variants under Brand).\n\nThe Setup Guide currently completes “Add your logo and brand color” when a logo is saved. Colour alone does not tick it. You can change colour and logos later. Quotes, invoices, and Social use this branding.',
  },
  {
    id: 'payments',
    q: 'How do I set payment details?',
    group: 'Core business setup',
    keywords: ['payments setup', 'bsb', 'stripe', 'payment threshold'],
    a: 'Three different money settings - none of them completes the others.\n\n1. Welcome-setup “Payments” - a recommendation amount for when card / Payment Protection is suggested on a quote. It is not your bank account.\n2. Bank transfer - BSB, account number, and bank name in Settings → Payments. That is what customers see for a transfer invoice.\n3. Card payments - connect Stripe in Settings → Payments or Integrations. The Guide ticks this when Stripe is active.\n\nMost tradies start with bank transfer. Stripe is optional. See Invoices & Payments and Payment Protection for how customers pay.',
  },
  {
    id: 'first-workflow',
    q: 'How do I add my first customer, quote, job and invoice?',
    group: 'Core business setup',
    keywords: ['first customer', 'first quote', 'first job', 'first invoice'],
    a: 'A simple first week:\n1. Add a customer in CRM (or capture a lead).\n2. Create a quote. The Setup Guide “first quote” item only completes after you send it - not while it is a draft.\n3. Open or create a job (from an accepted quote, or from Jobs).\n4. Send an invoice from the job or the invoice builder. There is no Setup Guide task for the first invoice today.\n\nDashboard shortcuts: New Lead, New Quote, New Job.',
  },
  {
    id: 'phone',
    q: 'How do I set up the phone?',
    group: 'Communications setup',
    keywords: ['phone setup', 'business phone', 'buy number'],
    a: 'A StitchedUp business number is optional for using the rest of the app. You need an active number for inbound AI answering and most SMS (quotes, invoices, Missed Call texts).\n\nBuy or port a number under Settings → Phone Number, finish compliance if asked, then keep the number active.\n\nFull detail: Phone & SMS - How do I set up a business phone number?',
  },
  {
    id: 'ai-receptionist',
    q: 'How do I go live with the AI Receptionist?',
    group: 'Communications setup',
    keywords: ['ai receptionist setup', 'live', 'configured', 'published'],
    a: 'Configured is not Live. Tested is not Live.\n\nTypical path:\n1. Complete AI Receptionist setup (greeting, services, hours, voice) and publish / save it.\n2. Assign an active StitchedUp business number for phone answering. Website chat does not need that number.\n3. Switch Live on when you want inbound calls answered.\n\nThe Setup Guide ticks AI receptionist when setup is fully done / published - not when you have only tested.\n\nFull detail: AI Receptionist (How do I set up…, Live vs Off, Does it need a phone number?).',
  },
  {
    id: 'missed-call',
    q: 'How do I set up Missed Call AI?',
    group: 'Communications setup',
    keywords: ['missed call ai setup', 'manual', 'auto'],
    a: 'Missed Call AI texts people who miss you on the number you configured. It is separate from Live AI Receptionist on a StitchedUp number.\n\nYou will set the number path, reply mode (Manual does not send automatically), qualification, and notifications, then test.\n\nThere is no Setup Guide task for Missed Call AI today.\n\nFull detail: Missed Call AI & Conversations.',
  },
  {
    id: 'reviews',
    q: 'How do I set up reviews?',
    group: 'Communications setup',
    keywords: ['reviews', 'google review link'],
    a: 'Two related pieces:\n- Review link - paste your Google review URL in Settings (also an optional wizard step). The Setup Guide ticks when a review link is saved.\n- Review requests - StitchedUp can send a request after a job. That is automation, not the same as only saving the link.\n\nSee Reviews & Growth for request timing and templates.',
  },
  {
    id: 'team-accountant',
    q: 'How do I invite my team or accountant?',
    group: 'Team & integrations',
    keywords: ['team invite', 'accountant invite', 'va', 'presets'],
    a: 'Only the owner invites from Settings → Team. Choose a role:\n- Tradesperson / Apprentice - assigned jobs only (same field access)\n- Office / VA - jobs, customers, quotes, invoices, and calendar across the business\n- Manager - business-wide operations; not Billing or Team admin\n- Accountant (when available) - Accounts only; does not use a team seat\n\nAn invite sent is not the same as that person being able to log in. They must accept. Pending invites do not use a seat until they join. The Setup Guide may tick “Invite your team” when an invite exists, even before they accept.\n\nFull detail: Team & Permissions. Accountant access: Accounts Help.',
  },
  {
    id: 'user-limit',
    q: 'How many users are included?',
    group: 'Team & integrations',
    keywords: ['five', 'seats', 'user limit'],
    a: 'Up to five team seats plus the owner. Seats count tradespeople, office / VA, and managers. Accountants do not use a team seat. Pending invites do not use a seat until they join. See Team & Permissions.',
  },
  {
    id: 'integrations',
    q: 'What can I connect to StitchedUp?',
    group: 'Team & integrations',
    keywords: ['integrations', 'stripe', 'meta', 'website leads'],
    a: 'None of these are required to finish the welcome setup. Connect them under Settings → Integrations (also linked from the wizard header).\n\nAvailable today:\n- Google Calendar - optional copy of jobs after they exist in StitchedUp\n- Google Business Profile\n- Stripe (card payments)\n- Facebook / Instagram (Social publish)\n- Website leads, where that card is shown\n\nXero and LinkedIn show as Coming soon - they are not live.\n\nYou can connect Calendar or Stripe from Settings even before you finish the wizard.',
  },
  {
    id: 'google-calendar',
    q: 'Does Google Calendar replace StitchedUp Calendar?',
    group: 'Team & integrations',
    keywords: ['google calendar', 'calendar setup', 'source of truth'],
    a: 'No. StitchedUp Calendar is the source of truth for jobs and availability. Google Calendar is an optional connection so booked jobs can copy out.\n\nTurn the connection off and jobs still live in StitchedUp. Connecting Google is a Setup Guide item; using the in-app calendar is not.\n\nSee Jobs & Scheduling for one-way export, cancel leftovers, and AI booking. See also: AI Receptionist - Does Google Calendar replace StitchedUp Calendar?',
  },
  {
    id: 'dashboard',
    q: 'How do I customise my dashboard?',
    group: 'Dashboard & mobile',
    keywords: [
      'dashboard customize',
      'dashboard customise',
      'dashboard customisation',
      'dashboard customization',
      'widgets',
      'restore',
    ],
    a: 'On the dashboard, open Customize dashboard.\n\nYou can show or hide cards, drag to reorder, and Restore defaults for your role. Those choices are yours on this business - a teammate can have a different layout.\n\nOwners usually see every card at first, including Setup Guide. Field staff see a shorter default. Accountants do not get this dashboard - they land in Accounts.\n\nThe Setup Guide card hides itself when the Guide is complete. You can also hide it in Customize.\n\nSome money or CRM cards stay unavailable if that person cannot open those areas.',
  },
  {
    id: 'pwa',
    q: 'How do I install StitchedUp on my phone?',
    group: 'Dashboard & mobile',
    keywords: ['mobile app', 'pwa', 'install', 'add to home screen'],
    a: 'StitchedUp works in the phone or desktop browser. You can also install it as an app-like shortcut (PWA).\n\nAndroid (Chrome, when the install prompt appears): use Install app on the banner. It may show after you have been in the app a short time.\n\niPhone / iPad (Safari): Share → Add to Home Screen. StitchedUp does not publish a separate App Store install for this PWA path.\n\nIf you dismiss the prompt, it can stay hidden for about a week. Installing on iPhone/iPad is what makes push notifications possible there - the toggle in Settings is not enough on its own.\n\nDesktop: use the browser as usual; some browsers also offer install.\n\nWe only document Chrome/Android and Safari/iOS this way. If your browser never offers install, keep using the website.',
  },
  {
    id: 'common-mistakes',
    q: 'What are common setup mistakes?',
    group: 'Troubleshooting',
    keywords: ['mistakes', 'confused', 'still open'],
    a: 'Watch for these:\n- Finishing or skipping the wizard and thinking all setup is done\n- Treating the welcome Payments screen as BSB / bank setup\n- Starting Stripe but it is not active yet\n- AI set up or tested, but Live is still off\n- Expecting phone or SMS features with no active StitchedUp number\n- Leaving Missed Call AI in Manual and expecting automatic texts\n- Treating Google Calendar as the main calendar\n- Turning push on without installing the app / allowing the subscription on this device\n- Sending a team invite and assuming they can already log in\n- Expecting a draft quote to complete the first-quote Guide task\n- Skipping the logo and wondering why the Guide is still incomplete',
  },
  {
    id: 'feature-missing',
    q: 'Why don’t I see a feature?',
    group: 'Troubleshooting',
    keywords: ['missing', 'cannot see', 'permissions'],
    a: 'Usual reasons:\n- Your role or preset does not include it (accountant has no jobs or Social; field staff see assigned jobs)\n- That area is not switched on for this workspace yet\n- You still need to finish the welcome setup or choose a plan on Billing\n- A setup step is still missing (no phone number, Stripe not active)\n\nIf you are mid welcome setup, Help itself may not open yet - finish or skip those screens first.',
  },
]

export const GETTING_STARTED_QUESTION_IDS = QUESTIONS.map((question) => question.id)

export const GETTING_STARTED_CATEGORY: HelpFaqCategory = {
  id: GETTING_STARTED_HELP_CATEGORY_ID,
  title: 'Getting Started',
  sidebarLabel: 'Getting Started',
  description: 'First week: welcome setup, Setup Guide, payments, phone, and dashboard.',
  icon: Rocket,
  chipIds: ['getting-started'],
  keywords: [
    'getting started',
    'onboarding',
    'setup guide',
    'first login',
    'business profile',
    'phone setup',
    'ai receptionist setup',
    'payments setup',
    'calendar setup',
    'google calendar',
    'mobile app',
    'pwa',
    'dashboard customize',
    'dashboard customisation',
    'team invite',
    'accountant invite',
  ],
  questions: QUESTIONS,
}

export const GETTING_STARTED_HELP_ARTICLE_ALIASES: Record<string, string> = {
  'getting-started-after-signup': 'getting-started-after-signup',
  'getting-started-required-optional': 'getting-started-required-optional',
  'getting-started-onboarding': 'getting-started-onboarding',
  'getting-started-skip-onboarding': 'getting-started-skip-onboarding',
  'getting-started-help-billing-gate': 'getting-started-help-billing-gate',
  'getting-started-reopen-onboarding': 'getting-started-reopen-onboarding',
  'getting-started-setup-guide': 'getting-started-setup-guide',
  'getting-started-task-completion': 'getting-started-task-completion',
  'getting-started-task-open': 'getting-started-task-open',
  'getting-started-skip-task': 'getting-started-skip-task',
  'getting-started-business-profile': 'getting-started-business-profile',
  'getting-started-branding': 'getting-started-branding',
  'getting-started-payments': 'getting-started-payments',
  'getting-started-first-workflow': 'getting-started-first-workflow',
  'getting-started-phone': 'getting-started-phone',
  'getting-started-ai-receptionist': 'getting-started-ai-receptionist',
  'getting-started-missed-call': 'getting-started-missed-call',
  'getting-started-reviews': 'getting-started-reviews',
  'getting-started-team-accountant': 'getting-started-team-accountant',
  'getting-started-integrations': 'getting-started-integrations',
  'getting-started-google-calendar': 'getting-started-google-calendar',
  'getting-started-dashboard': 'getting-started-dashboard',
  'getting-started-pwa': 'getting-started-pwa',
  'getting-started-common-mistakes': 'getting-started-common-mistakes',
  'getting-started-feature-missing': 'getting-started-feature-missing',
  'getting-started-how-quickly-setup': 'getting-started-after-signup',
  'how-quickly-setup': 'getting-started-after-signup',
  mobile: 'getting-started-pwa',
  'getting-started-mobile': 'getting-started-pwa',
  desktop: 'getting-started-pwa',
  'getting-started-desktop': 'getting-started-pwa',
  'va-team': 'getting-started-team-accountant',
  'getting-started-va-team': 'getting-started-team-accountant',
}
