import { Landmark } from 'lucide-react'
import type { HelpFaqCategory, HelpFaqQuestion } from '@/components/marketing/help/helpContent'

export const ACCOUNTS_HELP_CATEGORY_ID = 'accounts-bookkeeping'

export function accountsHelpArticleHref(questionId: string): string {
  return `/help?article=${ACCOUNTS_HELP_CATEGORY_ID}-${questionId}`
}

const ACCOUNTS_P0_QUESTIONS: readonly HelpFaqQuestion[] = [
  {
    id: 'accounts-overview',
    q: 'What is Accounts?',
    group: 'Getting started',
    keywords: ['accounts', 'bookkeeping', 'finance'],
    a: 'Accounts is where you keep the business’s books - not the customer invoice you send, and not your StitchedUp subscription.\n\nIf Accounts is enabled for your workspace, you can work with:\n- Banking (import and match bank lines)\n- Suppliers and purchase orders\n- Supplier bills\n- GST summary\n- Profit & Loss\n- Accountant access\n\nWho can use it:\n- Owner - finance admin, plus Billing and Team\n- Manager and Office / VA - intended finance view and day-to-day Accounts work where those pages are on\n- Accountant - finance workspace only (Accounts)\n- Field staff (tradesperson / apprentice) - no Accounts and no internal costing or profitability\n\nThree different “money” areas:\n- Invoices & Payments - customer money in\n- Accounts - bookkeeping, costs, and bank matching\n- Billing & Usage - what you pay StitchedUp for the product\n\nIf a section is not in your menu yet, it is not switched on for that workspace.',
  },
  {
    id: 'accounts-banking',
    q: 'How does Banking work?',
    group: 'Banking',
    keywords: ['banking', 'bank csv', 'bank reconciliation', 'reconcile'],
    a: 'If Accounts Banking is enabled for your workspace, Banking is how you bring bank lines into StitchedUp and match them to work you already recorded.\n\nToday that means:\n1. Add or pick a bank account in Accounts (you name it - it is a manual account).\n2. Import a CSV from your bank.\n3. Work through the reconciliation queue.\n\nThere is no live bank feed currently. StitchedUp does not log in to your bank or download transactions automatically.',
  },
  {
    id: 'accounts-bank-csv',
    q: 'How do I import a bank CSV?',
    group: 'Banking',
    keywords: ['bank csv', 'import', 'csv', 'preview'],
    a: 'In Accounts → Banking, choose the bank account, then upload the CSV your bank exported.\n\nStitchedUp previews the file, suggests how columns map (date, amount, description), and flags rows it cannot import (for example a bad date or a zero amount).\n\nCheck the preview, then commit the import. Those lines go into the reconciliation queue so you can match or ignore them.\n\nWhat happens next: open the queue and work unmatched lines. Importing does not mark anything as paid by itself.',
  },
  {
    id: 'accounts-bank-duplicates',
    q: 'What if I import the same file twice?',
    group: 'Banking',
    keywords: ['duplicate', 'same file', 'sha'],
    a: 'An exact copy of a file you already imported for that account is blocked. StitchedUp does not delete the first import - it simply will not load the same file again.\n\nIf you upload a different file that still has some of the same rows, those rows can show as likely duplicates. You can leave them out, or include them if you are sure they are new.\n\nDo not expect StitchedUp to wipe old imports. To fix a bad match, undo that reconciliation - do not try to “re-import the same CSV over the top.”',
  },
  {
    id: 'accounts-reconciliation',
    q: 'How does bank reconciliation work?',
    group: 'Banking',
    keywords: ['reconciliation', 'reconcile', 'match', 'queue'],
    a: 'Each imported line starts unmatched. You tell StitchedUp what it is.\n\nYou can:\n- Match or record a customer payment (money in against an invoice)\n- Match or pay a supplier bill (money out against a bill)\n- Match or create an expense\n- Mark a transfer between your own accounts\n- Ignore a line (personal, duplicate, opening balance, and similar)\n- Treat a Stripe payout as already recorded\n\nYou can undo a match if you chose the wrong action. Undo puts the line back in the queue. It does not delete the imported transaction.',
  },
  {
    id: 'accounts-live-bank-feed',
    q: 'Can I connect a live bank feed?',
    group: 'Banking',
    keywords: ['live bank feed', 'automatic sync', 'connect bank'],
    a: 'No, not currently.\n\nBanking is CSV import only. You download a file from your bank and upload it in Accounts.\n\nIf you see “Coming soon” on Banking, that workspace does not have Banking switched on yet.',
  },
  {
    id: 'accounts-supplier-bills',
    q: 'What is a supplier bill?',
    group: 'Suppliers & purchases',
    keywords: ['supplier bill', 'supplier', 'received'],
    a: 'A supplier bill is the record of what you owe a supplier - materials, a subcontractor invoice, or similar.\n\nDocument status (is the bill on the books?):\n- Draft - you are still entering it; it does not count yet\n- Received - it is a real cost on the bill date\n- Cancelled - ignored\n\nPayment status is separate (have you paid them?):\n- Unpaid, part paid, or paid\n\nYou can optionally link the bill to a job. A received bill affects job costing and Profit & Loss. Paying it later only settles cash - it does not create a second cost.',
  },
  {
    id: 'accounts-unpaid-bills',
    q: 'Do unpaid supplier bills still count?',
    group: 'Suppliers & purchases',
    keywords: ['unpaid', 'still count', 'accrual'],
    a: 'Yes. Once a bill is Received, it counts on the document date even if you have not paid the supplier yet.\n\nPayment status only tracks cash: unpaid, part paid, or paid. It does not decide whether the cost exists.\n\nExample: you receive a $2,200 bill dated 3 July and pay it on 20 August. July still holds the cost (and the GST on that bill). August holds the payment, not a new cost.',
  },
  {
    id: 'accounts-job-bills',
    q: 'How do I attach a supplier bill to a job?',
    group: 'Suppliers & purchases',
    keywords: ['job-linked', 'attach bill', 'cost of sales'],
    a: 'When you create or edit a supplier bill, pick the job it belongs to.\n\nA received job-linked bill contributes to that job’s cost and is treated as cost of sales on Profit & Loss.\n\nA received bill with no job is treated as an overhead / operating expense.\n\nLinking the wrong job moves the cost to the wrong job and can change cost of sales versus overhead. Change the job on the bill if you attached it too early.',
  },
  {
    id: 'accounts-supplier-payment',
    q: 'Why does paying the supplier not add another cost?',
    group: 'Suppliers & purchases',
    keywords: ['supplier payment', 'second cost', 'settle'],
    a: 'The supplier bill is the cost. Paying the bill (from Banking or by recording a payment) only settles what you owe and moves cash.\n\nDo not also raise a new expense for the same payment, or the job and Profit & Loss will look twice as expensive as they are.',
  },
  {
    id: 'accounts-job-costs',
    q: 'What counts as a job cost?',
    group: 'Job costing',
    keywords: ['job costing', 'job cost', 'what counts'],
    a: 'On the job profitability card, when supplier-bill accounting is enabled for your workspace, a job cost can include:\n- Received supplier bills linked to that job\n- Job expenses that are not linked to a supplier bill\n- Manual materials, labour, and fee figures you enter on the job\n\nThese do not count as a job cost:\n- Purchase orders (the order is not the bill)\n- Supplier payments (cash only)\n- An expense that is already linked to a supplier bill\n- Draft or cancelled bills\n\nTurn Job Costing on in Settings if you do not see the profitability card. Expenses still save if that switch is off.',
  },
  {
    id: 'accounts-double-counting',
    q: 'How do bills and expenses avoid double-counting?',
    group: 'Job costing',
    keywords: ['double-counting', 'linked expense', 'duplicate'],
    a: 'If you scanned a receipt and later entered the same supplier bill, link them.\n\nA linked expense is excluded from job costing so the bill is the one cost that counts.\n\nIf you leave both unlinked, StitchedUp can count both. Link them, or keep only one record for that purchase.',
  },
  {
    id: 'accounts-job-cost-gst',
    q: 'Are job costs GST-inclusive or ex-GST?',
    group: 'Job costing',
    keywords: ['ex-gst', 'inclusive', 'gst basis'],
    a: 'They are mixed on the job card today - that is intentional in the product, not a rounding bug.\n\n- Received supplier bills count at the ex-GST subtotal\n- Job expenses count at the recorded expense total (usually the receipt total, which often includes GST)\n\nProfit & Loss is different: when the business is GST-registered, P&L uses ex-GST figures and shows GST separately.\n\nIf the job card and P&L disagree, check which documents are job-linked and which amount each screen uses. See also: Why don’t my profit numbers match?',
  },
  {
    id: 'accounts-profit-loss',
    q: 'What is Profit & Loss?',
    group: 'Profit & Loss',
    keywords: ['profit and loss', 'p&l', 'period'],
    a: 'Profit & Loss is a period report for the whole business - revenue, cost of sales, and operating expenses - if Accounts Profit & Loss is enabled for your workspace.\n\nIt is not:\n- The profitability card on one job\n- The operational Reports page (`/reports`), which summarises job snapshots\n\nDefault period is this Australian financial year (1 July-30 June) in your business timezone. You can switch month, quarter, or a custom range.\n\nStitchedUp builds the report from records in your account. Check the figures with your accountant before you rely on them for decisions or lodgements.',
  },
  {
    id: 'accounts-pl-invoices',
    q: 'Which invoices count in Profit & Loss?',
    group: 'Profit & Loss',
    keywords: ['sent', 'paid', 'overdue', 'draft', 'voided'],
    a: 'Included: invoices that are sent, paid, or overdue.\n\nExcluded: draft and voided invoices.\n\nThe date is the document date: the issued date if you have one, otherwise the date the invoice was sent, otherwise the date it was created.\n\nPaying a customer later does not move that invoice into a new P&L month.',
  },
  {
    id: 'accounts-cost-of-sales',
    q: 'What is cost of sales vs operating expenses?',
    group: 'Profit & Loss',
    keywords: ['cost of sales', 'operating expenses', 'overhead'],
    a: 'Cost of sales: costs tied to a job - received job-linked supplier bills, and job expenses that are not linked to a bill.\n\nOperating expenses: overhead with no job - rent, fuel, or a supplier bill you left unlinked.\n\nLinking a bill or expense to a job is what moves it from overhead into cost of sales.',
  },
  {
    id: 'accounts-gst-summary',
    q: 'What is the GST summary?',
    group: 'GST',
    keywords: ['gst', 'gst summary', 'collected', 'paid'],
    a: 'GST summary is an estimate of GST collected and GST paid from records in StitchedUp:\n- GST on issued customer invoices (sent, paid, or overdue)\n- GST on expenses\n- GST on received supplier bills (when supplier-bill accounting is on)\n\nIt uses the document date, not the payment date.\n\nIt is not a lodged BAS. StitchedUp gives you an estimate based on the records in your account. Check your figures with your accountant or BAS agent before lodging.',
  },
  {
    id: 'accounts-document-date',
    q: 'Why does document date matter?',
    group: 'GST',
    keywords: ['document date', 'bill date', 'issued date'],
    a: 'Revenue, costs, and GST are recognised on the document date - the invoice issued date or the supplier bill date - not the day money left or entered the bank.\n\nPaying later does not move the sale or the cost into a new month. That is why an unpaid July bill still sits in July.',
  },
  {
    id: 'accounts-gst-payment-timing',
    q: 'Does paying an invoice or bill change GST timing?',
    group: 'GST',
    keywords: ['gst timing', 'cash', 'payment date'],
    a: 'No. The current GST summary is a document-date estimate.\n\nPaying a customer invoice or paying a supplier bill does not move that GST into the payment month.\n\nIf you need cash-basis GST for lodgement, confirm the method with your accountant - StitchedUp is not lodging BAS for you.',
  },
  {
    id: 'accounts-bas',
    q: 'Is the GST summary my BAS?',
    group: 'GST',
    keywords: ['bas', 'lodge', 'ato'],
    a: 'No. It is an on-screen estimate from your StitchedUp records.\n\nUse it to prepare, then have your accountant or registered BAS agent check and lodge. Do not treat the summary as a filed return.',
  },
  {
    id: 'accounts-accountant-access',
    q: 'What can an accountant see and do?',
    group: 'Accountant access',
    keywords: ['accountant', 'bookkeeper', 'invite'],
    a: 'If the Accountant login is available on your workspace, that person is finance-focused.\n\nThey can:\n- Use Accounts (overview, suppliers, bills, GST, Profit & Loss when those areas are on)\n- Import bank CSVs and reconcile\n- Scan and edit expenses (not delete them)\n- Create and edit suppliers and supplier bills, and record bill payments\n- View purchase orders and invoices\n- Export GST and Profit & Loss\n\nThey land in Accounts, not the main dashboard. See also: How do I invite an accountant?',
  },
  {
    id: 'accounts-accountant-limits',
    q: 'What can an accountant not access?',
    group: 'Accountant access',
    keywords: ['accountant', 'cannot', 'permissions'],
    a: 'An accountant login is intentionally narrow. They cannot:\n- Open the main dashboard, jobs, calendar, CRM, chat, quotes, or Social\n- Open operational Reports, Settings, or Billing\n- Manage the team\n- Create or change customer invoices or purchase orders\n- Delete expenses, bills, or suppliers\n\nIf they need jobs or quotes, invite them as Office / VA or Manager - not Accountant.',
  },
  {
    id: 'accounts-common-mistakes',
    q: 'What are common bookkeeping mistakes?',
    group: 'Troubleshooting',
    keywords: ['mistakes', 'double', 'bas', 'live bank feed'],
    a: 'Watch for these:\n- Recording a supplier payment as a new expense - the bill already holds the cost\n- Keeping the same purchase as a bill and an unlinked expense\n- Expecting an unpaid received bill not to hit the job or Profit & Loss\n- Thinking in payment dates instead of document dates\n- Assuming a live bank feed exists (it does not - use CSV)\n- Trying to import the exact same CSV again\n- Treating the GST summary as a lodged BAS\n- Expecting a purchase order to count as a cost before there is a received bill\n- Treating one job’s profitability card as the same as Accounts Profit & Loss\n- Linking a supplier bill to the wrong job',
  },
  {
    id: 'accounts-profit-numbers',
    q: 'Why don’t my profit numbers match?',
    group: 'Troubleshooting',
    keywords: ['profit numbers', 'reports', 'job card', 'p&l'],
    a: 'Three screens answer different questions.\n\n1. Job profitability card - one job. Can include draft invoice revenue on that job. Uses mixed GST bases (bills ex-GST, expenses usually at receipt total).\n2. Reports - operational snapshot of jobs (completed-job profit and similar). Accountants cannot open this page.\n3. Accounts Profit & Loss - the period for the whole business. Counts sent, paid, and overdue invoices only (not drafts). Uses document dates and ex-GST figures when you are GST-registered.\n\nThey will not always match. That is expected. Pick the screen that matches the question you are asking.',
  },
]

const ACCOUNTS_P1_QUESTIONS: readonly HelpFaqQuestion[] = [
  {
    id: 'accounts-suppliers',
    q: 'How do suppliers work?',
    group: 'Suppliers & purchases',
    keywords: ['supplier', 'abn', 'vendor'],
    a: 'Suppliers are the businesses you buy from. Add them under Accounts → Suppliers with name, ABN, and payment terms if you have them.\n\nBills, purchase orders, and some expenses can point at a supplier so spend rolls up in one place.\n\nUse one supplier record per business. If you created a duplicate, keep using the one that already has bills attached.',
  },
  {
    id: 'accounts-purchase-orders',
    q: 'How do purchase orders work?',
    group: 'Suppliers & purchases',
    keywords: ['purchase order', 'po'],
    a: 'A purchase order is what you asked the supplier to supply - not the bill, and not a job cost.\n\nCreate a PO against a supplier (and a job if you want). When the supplier invoice arrives, turn it into a received bill. Only that received bill counts as a cost.\n\nCreating and changing PO status is an owner or admin task. Accountants can view POs but cannot create or edit them.',
  },
  {
    id: 'accounts-po-status',
    q: 'What does a purchase order status mean?',
    group: 'Suppliers & purchases',
    keywords: ['draft', 'approved', 'sent', 'received', 'cancelled'],
    a: 'Typical path: Draft → Approved → Sent → (partly received) → Received. You can cancel from most open steps.\n\nReceived on a PO means the goods or work turned up - it still does not post a job cost. Post the supplier bill for that.\n\nDraft or cancelled POs should not be turned into bills.',
  },
  {
    id: 'accounts-record-payment',
    q: 'How do I record a supplier payment?',
    group: 'Suppliers & purchases',
    keywords: ['record payment', 'pay bill'],
    a: 'Open the received bill and record a payment, or match a bank line to that bill in Banking.\n\nThat marks the bill unpaid, part paid, or paid. It does not add another job cost.\n\nIf you also create an expense for the same payment, you will double-count.',
  },
  {
    id: 'accounts-bank-match-targets',
    q: 'What can I match a bank transaction to?',
    group: 'Banking',
    keywords: ['match', 'customer payment', 'stripe payout'],
    a: 'Money in: a customer payment against an invoice, or a Stripe payout you have already recorded.\n\nMoney out: a supplier bill payment or an expense (match an existing one, or create one from the line).\n\nTransfers: movement between your own accounts.\n\nIgnore: personal, duplicate, opening balance, or non-business lines.\n\nIf Accounts Banking is not enabled, this queue is not in the menu.',
  },
  {
    id: 'accounts-export',
    q: 'How do I export GST and Profit & Loss?',
    group: 'Profit & Loss',
    keywords: ['export', 'csv'],
    a: 'On GST summary and on Profit & Loss, use the export when those pages are enabled. StitchedUp downloads a CSV of the on-screen period.\n\nThat file is still an estimate from your records - not a lodged BAS and not a signed financial statement.',
  },
  {
    id: 'accounts-add-expense',
    q: 'How do I add an expense?',
    group: 'Job costing',
    keywords: ['add expense', 'scan', 'receipt'],
    a: 'On Expenses or a job, use Scan receipt - that is the usual path. StitchedUp reads the file, you confirm the details, then save.\n\nIf Accounts Banking is on, matching or creating an expense from a bank line is another way an expense can appear. There is no separate “type a receipt-free expense” button on the Expenses hub.\n\nSee Expenses & Job Costing for file types and scan limits.',
  },
  {
    id: 'accounts-job-vs-overhead',
    q: 'What is a job expense vs an overhead expense?',
    group: 'Job costing',
    keywords: ['overhead', 'general', 'job expense'],
    a: 'A job expense is linked to a job. It can sit in job costing (unless it is also linked to a supplier bill) and in cost of sales.\n\nAn overhead expense has no job. It is operating expense - the cost of running the business, not one job.\n\nYou can change the job link later. Changing it moves where Profit & Loss and the job card pick it up.',
  },
  {
    id: 'accounts-receipt-scans',
    q: 'How do receipt scans work?',
    group: 'Job costing',
    keywords: ['receipt scan', 'textract'],
    a: 'Upload a photo or PDF. StitchedUp reads vendor, date, and amounts for you to confirm. JPEG, PNG, WebP, and PDF are supported. Your plan includes 100 receipt pages per calendar month; scanning pauses when that is used - there is no paid overage yet.\n\nCheck remaining pages on Billing under Expense Receipt Scanning. That Billing allowance is your StitchedUp plan, not a bookkeeping fee.',
  },
  {
    id: 'accounts-invite-accountant',
    q: 'How do I invite an accountant?',
    group: 'Accountant access',
    keywords: ['invite accountant', 'preset'],
    a: 'If Accountant is available on Settings → Team, the owner chooses Accountant and sends the invite.\n\nThey get a finance-only login and do not use a team seat. They will not see jobs, CRM, or quotes. If they need those, invite them as Office / VA or Manager instead - they will see more than the books, and they will use a team seat.',
  },
]

export const ACCOUNTS_P0_QUESTION_IDS = ACCOUNTS_P0_QUESTIONS.map((question) => question.id)
export const ACCOUNTS_P1_QUESTION_IDS = ACCOUNTS_P1_QUESTIONS.map((question) => question.id)

export const ACCOUNTS_BOOKKEEPING_CATEGORY: HelpFaqCategory = {
  id: ACCOUNTS_HELP_CATEGORY_ID,
  title: 'Accounts & Bookkeeping',
  sidebarLabel: 'Accounts',
  description: 'Banking, supplier bills, job costs, GST summary, and Profit & Loss.',
  icon: Landmark,
  chipIds: ['accounts'],
  keywords: [
    'accounts',
    'bookkeeping',
    'banking',
    'bank csv',
    'bank reconciliation',
    'reconcile',
    'reconciliation',
    'supplier',
    'supplier bill',
    'purchase order',
    'job costing',
    'profit and loss',
    'p&l',
    'gst',
    'accountant',
    'bas',
  ],
  questions: [...ACCOUNTS_P0_QUESTIONS, ...ACCOUNTS_P1_QUESTIONS],
}

export const ACCOUNTS_HELP_ARTICLE_ALIASES: Record<string, string> = {
  'accounts-overview': 'accounts-bookkeeping-accounts-overview',
  'accounts-banking': 'accounts-bookkeeping-accounts-banking',
  'accounts-bank-csv': 'accounts-bookkeeping-accounts-bank-csv',
  'accounts-bank-duplicates': 'accounts-bookkeeping-accounts-bank-duplicates',
  'accounts-reconciliation': 'accounts-bookkeeping-accounts-reconciliation',
  'accounts-live-bank-feed': 'accounts-bookkeeping-accounts-live-bank-feed',
  'accounts-supplier-bills': 'accounts-bookkeeping-accounts-supplier-bills',
  'accounts-unpaid-bills': 'accounts-bookkeeping-accounts-unpaid-bills',
  'accounts-job-bills': 'accounts-bookkeeping-accounts-job-bills',
  'accounts-supplier-payment': 'accounts-bookkeeping-accounts-supplier-payment',
  'accounts-job-costs': 'accounts-bookkeeping-accounts-job-costs',
  'accounts-double-counting': 'accounts-bookkeeping-accounts-double-counting',
  'accounts-job-cost-gst': 'accounts-bookkeeping-accounts-job-cost-gst',
  'accounts-profit-loss': 'accounts-bookkeeping-accounts-profit-loss',
  'accounts-pl-invoices': 'accounts-bookkeeping-accounts-pl-invoices',
  'accounts-cost-of-sales': 'accounts-bookkeeping-accounts-cost-of-sales',
  'accounts-gst-summary': 'accounts-bookkeeping-accounts-gst-summary',
  'accounts-document-date': 'accounts-bookkeeping-accounts-document-date',
  'accounts-gst-payment-timing': 'accounts-bookkeeping-accounts-gst-payment-timing',
  'accounts-bas': 'accounts-bookkeeping-accounts-bas',
  'accounts-accountant-access': 'accounts-bookkeeping-accounts-accountant-access',
  'accounts-accountant-limits': 'accounts-bookkeeping-accounts-accountant-limits',
  'accounts-common-mistakes': 'accounts-bookkeeping-accounts-common-mistakes',
  'accounts-profit-numbers': 'accounts-bookkeeping-accounts-profit-numbers',
  'accounts-suppliers': 'accounts-bookkeeping-accounts-suppliers',
  'accounts-purchase-orders': 'accounts-bookkeeping-accounts-purchase-orders',
  'accounts-po-status': 'accounts-bookkeeping-accounts-po-status',
  'accounts-record-payment': 'accounts-bookkeeping-accounts-record-payment',
  'accounts-bank-match-targets': 'accounts-bookkeeping-accounts-bank-match-targets',
  'accounts-export': 'accounts-bookkeeping-accounts-export',
  'accounts-add-expense': 'accounts-bookkeeping-accounts-add-expense',
  'accounts-job-vs-overhead': 'accounts-bookkeeping-accounts-job-vs-overhead',
  'accounts-receipt-scans': 'accounts-bookkeeping-accounts-receipt-scans',
  'accounts-invite-accountant': 'accounts-bookkeeping-accounts-invite-accountant',
  'reporting-track-payments': 'invoices-payments-payment-status',
}
