import { Users } from 'lucide-react'
import type { HelpFaqCategory, HelpFaqQuestion } from '@/components/marketing/help/helpContent'

export const CRM_HELP_CATEGORY_ID = 'leads-crm'

const QUESTIONS: readonly HelpFaqQuestion[] = [
  {
    id: 'crm-overview',
    q: 'What is CRM in StitchedUp?',
    group: 'Getting started',
    keywords: ['crm', 'what is crm', 'customer records'],
    a: 'CRM is the people list. Open it from the sidebar as CRM (there is no separate Leads page).\n\nEach customer record holds contact details, how they arrived (source), tags, notes, and the jobs, quotes, invoices, and conversations linked to them.\n\nCRM is not the job pipeline. Stages live on jobs. Filters on the CRM list (for example people with an active job) are shortcuts - they are not a second set of stages.',
  },
  {
    id: 'crm-lead-vs-customer',
    q: 'What is the difference between a lead and a customer?',
    group: 'Leads & customers',
    keywords: ['lead vs customer', 'convert lead', 'lead'],
    a: 'StitchedUp does not keep a separate Lead record and Customer record. The person is stored as a customer as soon as they are added.\n\nWhen people say “lead” they usually mean:\n- a new enquiry\n- a customer with new work\n- a job sitting in New Lead on the job board\n- or the source that brought them in\n\nThere is no Convert lead to customer step. Creating a quote, job, or invoice does not turn the person into a different type of record.',
  },
  {
    id: 'crm-add-customer',
    q: 'How do I add someone?',
    group: 'Leads & customers',
    keywords: ['add customer', 'new lead', 'manual leads'],
    a: 'Two paths:\n\nCRM → Add Customer - saves the person only. No job is created.\n\nJobs → New Lead - saves the person and opens a new job (usually in New Lead). If New Lead matches an existing phone, StitchedUp reuses that customer and still creates another job.\n\nWebsite and AI capture also create or reuse a customer and typically add a job. See How do website leads get into CRM?',
  },
  {
    id: 'new-lead',
    q: 'What happens when a new lead comes in?',
    group: 'Leads & customers',
    keywords: ['new lead comes in', 'enquiry'],
    a: 'The person is saved as a customer (or an existing customer is reused). New work is usually a new job, often in New Lead.\n\nAI Receptionist and Missed Call AI also appear in Conversations. When a name and phone are captured, that thread links to the customer.\n\nThis does not convert a lead into a customer - the customer record is already there. See What is the difference between a lead and a customer?',
  },
  {
    id: 'replace-crm',
    q: 'Does StitchedUp replace a CRM?',
    group: 'Getting started',
    keywords: ['replace crm'],
    a: 'For most trade businesses, yes. StitchedUp includes CRM for customer records, sources, tags, notes, and the jobs, quotes, and invoices attached to those people. It is not a separate sales-stage CRM. Job stages live on Jobs.',
  },
  {
    id: 'crm-lead-source',
    q: 'Where did this lead come from?',
    group: 'Pipeline & sources',
    keywords: ['lead source', 'ai receptionist', 'web form', 'manual', 'referral'],
    a: 'Each customer has a source you can see and edit:\n- AI Receptionist - website chat or live voice (and some missed-call bookings) when a new customer is created\n- Web Form - Website Leads / webhook ingest (including GHL-style posts)\n- Manual - you added them in CRM or Jobs → New Lead\n- Referral - you chose Referral\n- Other - you chose Other\n\nIf a later enquiry matches an existing person, the original source is usually left as-is. Source is not full ad attribution (clicks and campaign IDs on a website submission stay on that submission, not as a separate CRM source).',
  },
  {
    id: 'crm-source-integrations',
    q: 'Does Google, Meta or GHL become the lead source?',
    group: 'Pipeline & sources',
    keywords: ['google', 'meta', 'facebook', 'ghl lead'],
    a: 'No. Those names are not separate CRM source values.\n\nA GHL or website webhook still stores the customer as Web Form. Google Calendar, Google Business Profile, and Facebook/Instagram are other connections - they do not set a Google or Meta source on the customer.\n\nClick IDs (for example from ads) may sit on a website submission. They do not rename the CRM source.',
  },
  {
    id: 'crm-vs-job-pipeline',
    q: 'How is CRM different from the job pipeline?',
    group: 'Pipeline & sources',
    keywords: ['job pipeline', 'crm vs jobs', 'lead stage'],
    a: 'CRM is people. The job pipeline is work.\n\nMoving a job (New Lead → Contacted → Quote Sent, and so on) does not change the customer into another type of record and does not give the customer a stage.\n\nOpen Jobs to change stages. Open CRM to find the person and their related work.',
  },
  {
    id: 'crm-job-stages',
    q: 'What are the job pipeline stages?',
    group: 'Pipeline & sources',
    keywords: ['job pipeline', 'lead stage', 'new lead', 'cancelled'],
    a: 'Stages belong to the job, not the customer:\n- New Lead\n- Contacted\n- Quote Sent\n- Quote Accepted\n- In Progress\n- Job Done\n- Invoice Sent\n- Paid\n- Cancelled\n\nThere is no Scheduled stage. You can put a date on the calendar without that being a pipeline column.\n\nA draft quote does not move the job. Sending or accepting a quote, sending an invoice, or taking payment can. See Jobs & Scheduling.',
  },
  {
    id: 'crm-website-leads',
    q: 'How do website leads get into CRM?',
    group: 'Website leads & integrations',
    keywords: ['website lead', 'website leads', 'web form'],
    a: 'Turn on a Website Leads connection under Settings → Integrations. Your site (or an automation) posts the enquiry to the address StitchedUp gives you.\n\nStitchedUp matches phone or email to an existing customer when it can, or creates one, then creates a new job unless the same submission is sent twice. The customer source is Web Form.\n\nYou need the connection active and a usable email or phone in the mapping. There is no hosted StitchedUp form to paste on a website today.',
  },
  {
    id: 'crm-website-integrations',
    q: 'What website lead connections are supported?',
    group: 'Website leads & integrations',
    keywords: ['wordpress', 'wix', 'webhook'],
    a: 'The Website Leads page supports posting into StitchedUp from:\n- WordPress\n- Wix\n- GoHighLevel (as a webhook into StitchedUp, not a two-way CRM sync)\n- a generic / custom webhook\n\nSquarespace and similar tools usually go through an automation that posts to the same webhook. This is enquiry ingest, not a sync of your whole external CRM.',
  },
  {
    id: 'crm-ghl',
    q: 'Is there a native GHL CRM sync?',
    group: 'Website leads & integrations',
    keywords: ['ghl', 'ghl lead', 'gohighlevel'],
    a: 'No. There is no two-way GoHighLevel CRM sync.\n\nWhere GHL is configured, it can post new enquiries into StitchedUp (Website Leads or a webhook). Those people are stored as Web Form customers with a new job. StitchedUp does not keep GHL contacts, pipelines, or opportunities in lockstep.',
  },
  {
    id: 'ghl-integration',
    q: 'Does StitchedUp integrate with GoHighLevel?',
    group: 'Website leads & integrations',
    keywords: ['gohighlevel', 'ghl integration'],
    a: 'For new website/GHL enquiries, yes - as webhook-style lead ingest, not a full GHL CRM sync. People arrive as Web Form customers. See Is there a native GHL CRM sync?',
  },
  {
    id: 'crm-meta-google-leads',
    q: 'Do you support Meta Lead Ads or Google Lead Forms?',
    group: 'Website leads & integrations',
    keywords: ['meta lead ads', 'google lead forms'],
    a: 'Not as a direct live feed into CRM. There is no Meta Lead Ads or Google Lead Forms ingest in StitchedUp today.\n\nA website form that posts to Website Leads still arrives as Web Form. Connecting Facebook or Google for Social or Calendar is separate and does not create those CRM sources.',
  },
  {
    id: 'crm-import',
    q: 'Can I import customers?',
    group: 'Duplicates & merge',
    keywords: ['import customers', 'import leads', 'csv', 'bulk import'],
    a: 'Not currently. There is no CRM CSV upload, template, or bulk-import wizard.\n\nAdd people with CRM → Add Customer, Jobs → New Lead, or a Website Leads connection. Bank CSV import is for Accounts, not customers.',
  },
  {
    id: 'import-customers',
    q: 'Can I import existing customers?',
    group: 'Duplicates & merge',
    keywords: ['import existing customers'],
    a: 'Not via a CRM bulk import. There is no customer CSV import today. Use Add Customer, New Lead, or Website Leads. See Can I import customers?',
  },
  {
    id: 'crm-duplicates',
    q: 'How do duplicate customers work?',
    group: 'Duplicates & merge',
    keywords: ['duplicate customer', 'duplicate', 'same phone'],
    a: 'StitchedUp does not block a second customer with the same phone or email. CRM can warn when another record shares a phone or email.\n\nSome capture paths reuse a match (New Lead by exact phone; website ingest by phone or email) and still add a new job. If a match is unclear, another customer can still be created.\n\nOne customer can have many jobs. That is normal - it is not automatically a duplicate person.',
  },
  {
    id: 'crm-merge',
    q: 'How do I merge customers?',
    group: 'Duplicates & merge',
    keywords: ['merge customer', 'merge'],
    a: 'Only the business owner can merge. On the customer, open Merge, pick the other record, and choose which details to keep on the primary (surviving) record.\n\nThe duplicate is archived and linked to the survivor. Jobs, quotes, invoices, and conversations move across. Tags are combined. Notes from the duplicate are appended. The primary source is kept.\n\nReview both records carefully before you confirm. Merges cannot be undone in the product today.',
  },
  {
    id: 'crm-unmerge',
    q: 'Can I undo a customer merge?',
    group: 'Duplicates & merge',
    keywords: ['unmerge', 'undo merge'],
    a: 'No. There is no Unmerge in the product. The archived duplicate stays linked to the surviving customer. If a merge was wrong, fix details on the survivor and keep using that record.',
  },
  {
    id: 'crm-edit-customer',
    q: 'How do I edit a customer?',
    group: 'Customer records',
    keywords: ['edit customer'],
    a: 'Open the customer in CRM and use Edit. You can change name, phone, email, address, trade, source, tags, and notes.\n\nSaving an edit does not move job stages or convert the person. Merged (archived) records are not edited - open the surviving customer instead.',
  },
  {
    id: 'crm-tags',
    q: 'How do tags work?',
    group: 'Customer records',
    keywords: ['customer tags', 'tags', 'vip'],
    a: 'Tags sit on the customer (for example VIP, Follow up). You can filter the CRM list by tag.\n\nThe business can add custom tags. Managing the tag list (create, rename, archive) is an owner task under Settings → customer tags. Applying a tag on a customer is available to people who can edit CRM.',
  },
  {
    id: 'crm-notes-activity',
    q: 'How do notes and activity work?',
    group: 'Customer records',
    keywords: ['customer notes', 'customer activity', 'timeline'],
    a: 'Notes are one field on the customer. You can edit it; there is no version history of every past note.\n\nActivity is a timeline built from what already happened - customer created, jobs, quotes, invoices, and AI conversations - not a separate diary you type into. A notes change can show as an activity using the last save time.',
  },
  {
    id: 'crm-search-filter',
    q: 'How do I search and filter CRM?',
    group: 'Customer records',
    keywords: ['search crm', 'filter', 'segments'],
    a: 'Search covers name, email, suburb, and phone.\n\nYou can also filter by source, tag, and list shortcuts such as active job, outstanding or overdue invoice, pending quote, repeat customer, AI Receptionist source, or no recent job.\n\nMerged/archived people are hidden from the normal list. If you cannot find someone, clear filters and check they were not merged.',
  },
  {
    id: 'crm-assignment',
    q: 'Can I assign a customer to a team member?',
    group: 'Customer records',
    keywords: ['assign customer', 'assignment', 'assigned'],
    a: 'No. Customers are not assigned to staff.\n\nJobs can have an assignee. Field staff typically see jobs assigned to them, not a personal CRM book. Filter jobs by assignee on Jobs, not on CRM.',
  },
  {
    id: 'crm-create-job',
    q: 'How do I create a job from CRM?',
    group: 'Quotes & jobs',
    keywords: ['create job', 'new job'],
    a: 'Open the customer and choose Create Job. The new job is linked to that person and usually starts in New Lead.\n\nThat does not convert the customer. If you pick the wrong person, the job sits on the wrong record - check the name first.\n\nOwners and office/VA logins can create jobs. Do not assume every manager preset can; if Create Job fails, use an owner or office login or ask the owner to create the job.',
  },
  {
    id: 'crm-create-quote',
    q: 'How do I create a quote from CRM?',
    group: 'Quotes & jobs',
    keywords: ['create quote'],
    a: 'On the customer, choose Create Quote. If they have one job, StitchedUp takes you there; if they have several, pick a job. A draft quote does not move the job stage. Sending or accepting the quote can update that job.\n\nIf they have no job yet, create a job first (Create Job), then quote it. Creating a quote does not convert the customer.',
  },
  {
    id: 'crm-create-invoice',
    q: 'How do I create an invoice from CRM?',
    group: 'Quotes & jobs',
    keywords: ['create invoice'],
    a: 'On the customer, open More actions and choose Create Invoice. If they have one job, you go to that job’s invoice flow; if they have several, pick a job.\n\nInvoicing does not change the customer into another type of record. Prefer starting from a job so the invoice stays attached to the right work.',
  },
  {
    id: 'crm-no-conversion',
    q: 'Does creating a job, quote or invoice convert the lead?',
    group: 'Quotes & jobs',
    keywords: ['convert lead to customer', 'conversion'],
    a: 'No. There is no lead-to-customer conversion step. The person is already a customer record. Job, quote, and invoice actions add or update work. They do not change the person’s type.',
  },
  {
    id: 'crm-call-conversations',
    q: 'How do Call and Conversations work from CRM?',
    group: 'Quotes & jobs',
    keywords: ['call customer', 'customer conversations', 'conversations'],
    a: 'On the customer:\n- Call opens the phone number on your device (if one is saved). It does not log a call in CRM by itself.\n- Conversations opens the inbox filtered to that person.\n\nThe button is Conversations, not Chat. For SMS and missed-call threads, see Phone & SMS and Missed Call AI.',
  },
  {
    id: 'crm-permissions',
    q: 'Who can use CRM?',
    group: 'Team & permissions',
    keywords: ['crm permissions', 'office admin', 'field', 'accountant'],
    a: 'Owner - full CRM, including merge and the tag library.\nOffice / VA - view and edit customers; cannot merge.\nManager - business-wide CRM as part of day-to-day operations.\nTradesperson / Apprentice - no CRM. The CRM menu is hidden.\nAccountant - no CRM; they use Accounts.\nQuotes-only and Social-only are limited product modes, not staff roles. Social-only cannot open CRM. Quotes-only generally can.\n\nSee Team & Permissions.',
  },
  {
    id: 'crm-common-mistakes',
    q: 'What are common CRM mistakes?',
    group: 'Troubleshooting',
    keywords: ['mistakes', 'duplicate'],
    a: 'Watch for these:\n- Adding a new customer instead of opening the existing one\n- Thinking a lead converts into a customer\n- Treating CRM as the job pipeline\n- Looking for a customer CSV import\n- Expecting Google, Meta, or GHL as separate source labels\n- Merging the wrong pair (owner only; cannot undo)\n- Expecting a draft quote to move the job\n- Waiting for website leads with no Website Leads connection\n- Creating a job on the wrong customer\n- Trying to assign a customer to a staff member\n- Treating source as full advertising attribution',
  },
  {
    id: 'crm-customer-missing',
    q: 'Why don’t I see this customer or CRM?',
    group: 'Troubleshooting',
    keywords: ['missing customer', 'cannot see crm', 'empty crm'],
    a: 'Common reasons:\n- Your login does not include CRM (tradesperson / apprentice, accountant, Social-only)\n- The person was merged - open the surviving customer\n- Search or filters are still on (source, tag, or a list shortcut)\n- You are on Jobs, not CRM\n\nField staff do not see CRM in the menu. Ask the owner if you need customer records opened for you, or a different role.',
  },
]

export const CRM_HELP_QUESTION_IDS = QUESTIONS.map((question) => question.id)

export const LEADS_CRM_CATEGORY: HelpFaqCategory = {
  id: CRM_HELP_CATEGORY_ID,
  title: 'Leads & CRM',
  sidebarLabel: 'Leads & CRM',
  description: 'Keep customer details, lead source, notes, tags and related work together.',
  icon: Users,
  chipIds: ['leads-crm'],
  keywords: [
    'crm',
    'lead source',
    'lead vs customer',
    'website lead',
    'website leads',
    'ghl lead',
    'import customers',
    'import leads',
    'duplicate customer',
    'merge customer',
    'customer tags',
    'customer notes',
    'customer activity',
    'assign customer',
    'lead stage',
    'job pipeline',
    'create job',
    'create quote',
    'create invoice',
    'call customer',
    'customer conversations',
  ],
  questions: QUESTIONS,
}

export const CRM_HELP_ARTICLE_ALIASES: Record<string, string> = {
  'crm-overview': 'leads-crm-crm-overview',
  'crm-lead-vs-customer': 'leads-crm-crm-lead-vs-customer',
  'crm-add-customer': 'leads-crm-crm-add-customer',
  'crm-lead-source': 'leads-crm-crm-lead-source',
  'crm-source-integrations': 'leads-crm-crm-source-integrations',
  'crm-vs-job-pipeline': 'leads-crm-crm-vs-job-pipeline',
  'crm-job-stages': 'leads-crm-crm-job-stages',
  'crm-website-leads': 'leads-crm-crm-website-leads',
  'crm-website-integrations': 'leads-crm-crm-website-integrations',
  'crm-ghl': 'leads-crm-crm-ghl',
  'crm-meta-google-leads': 'leads-crm-crm-meta-google-leads',
  'crm-import': 'leads-crm-crm-import',
  'crm-duplicates': 'leads-crm-crm-duplicates',
  'crm-merge': 'leads-crm-crm-merge',
  'crm-unmerge': 'leads-crm-crm-unmerge',
  'crm-edit-customer': 'leads-crm-crm-edit-customer',
  'crm-tags': 'leads-crm-crm-tags',
  'crm-notes-activity': 'leads-crm-crm-notes-activity',
  'crm-search-filter': 'leads-crm-crm-search-filter',
  'crm-assignment': 'leads-crm-crm-assignment',
  'crm-create-job': 'leads-crm-crm-create-job',
  'crm-create-quote': 'leads-crm-crm-create-quote',
  'crm-create-invoice': 'leads-crm-crm-create-invoice',
  'crm-no-conversion': 'leads-crm-crm-no-conversion',
  'crm-call-conversations': 'leads-crm-crm-call-conversations',
  'crm-permissions': 'leads-crm-crm-permissions',
  'crm-common-mistakes': 'leads-crm-crm-common-mistakes',
  'crm-customer-missing': 'leads-crm-crm-customer-missing',
  'manual-leads': 'leads-crm-crm-add-customer',
  'leads-crm-manual-leads': 'leads-crm-crm-add-customer',
  'leads-crm-import-customers': 'leads-crm-crm-import',
  'leads-crm-ghl-integration': 'leads-crm-crm-ghl',
  'leads-crm-reactivate-jobs': 'jobs-scheduling-reactivate-jobs',
  'reactivate-jobs': 'jobs-scheduling-reactivate-jobs',
}
