import { Calendar } from 'lucide-react'
import type { HelpFaqCategory, HelpFaqQuestion } from '@/components/marketing/help/helpContent'

export const JOBS_SCHEDULING_HELP_CATEGORY_ID = 'jobs-scheduling'

const QUESTIONS: readonly HelpFaqQuestion[] = [
  {
    id: 'calendar-overview',
    q: 'What is StitchedUp Calendar?',
    group: 'Getting started',
    keywords: ['calendar', 'job calendar', 'week view', 'unscheduled'],
    a: 'Calendar (sidebar → Calendar) is the week view of jobs that already have a start time in StitchedUp.\n\nToday it is a Monday-Sunday grid, roughly 6:00 am-8:00 pm, in 30-minute slots. There is no separate day, month, team, or agenda switcher on this page.\n\nScheduled jobs appear as blocks you can drag. Jobs without a start time sit in the unscheduled queue (a drawer on a phone).\n\nThe calendar is built from StitchedUp job times - not from Google Calendar, and not from a job’s pipeline stage.',
  },
  {
    id: 'calendar-stage-vs-schedule',
    q: 'How is the calendar different from job stage and assignment?',
    group: 'Getting started',
    keywords: ['job pipeline', 'assignment', 'scheduled', 'when'],
    a: 'Three separate things:\n- Calendar - when the work is booked\n- Pipeline - where the job sits in the workflow (New Lead, Contacted, Quote Sent, and so on)\n- Assignment - who is doing it\n\nExamples:\n- Contacted + unscheduled - you spoke to them, but there is no calendar block yet\n- In Progress + scheduled - work is underway and has a time on Calendar\n- Scheduled + unassigned - there is a time, but nobody is picked yet\n\nThere is no Scheduled pipeline stage. Putting a job on the calendar does not move the stage. Assigning a person does not put a time on the calendar.',
  },
  {
    id: 'calendar-source-of-truth',
    q: 'Is Google Calendar the source of truth?',
    group: 'Getting started',
    keywords: ['source of truth', 'google calendar', 'authoritative'],
    a: 'No. StitchedUp Calendar is the booking source of truth.\n\nGoogle Calendar is an optional one-way copy of jobs after they exist in StitchedUp. Google does not decide availability, overwrite StitchedUp jobs, or block AI booking slots.\n\nIf Google is disconnected or a copy fails, bookings still live in StitchedUp. See How do I connect Google Calendar?',
  },
  {
    id: 'job-pipeline',
    q: 'How does the job pipeline work?',
    group: 'Getting started',
    keywords: ['job pipeline', 'lead to completion', 'stages'],
    a: 'Jobs move through a fixed pipeline: New Lead, Contacted, Quote Sent, Quote Accepted, In Progress, Job Done, Invoice Sent, Paid, and Cancelled. Those stages belong to the job, not the CRM customer.\n\nThere is no Scheduled stage - calendar dates are separate. A draft quote does not move the stage. See Leads & CRM - How is CRM different from the job pipeline?',
  },
  {
    id: 'lead-to-completion',
    q: 'Can I track jobs from lead to completion?',
    group: 'Getting started',
    keywords: ['lead to completion', 'workflow'],
    a: 'Yes. That is one of the core purposes of StitchedUp. The job stays in one connected workflow from first enquiry through to completion and payment. The calendar only shows when a start time exists - it is not a second pipeline.',
  },
  {
    id: 'schedule-jobs',
    q: 'How do I put a job on the calendar?',
    group: 'Scheduling jobs',
    keywords: ['schedule job', 'schedule jobs', 'book job', 'put on calendar'],
    a: 'A job appears on Calendar when it has a scheduled start time - not merely a preferred date on the job card.\n\nUsual paths:\n- Calendar → Schedule Job, and pick customer, time, and details\n- Open a job from the unscheduled queue and give it a start time\n- Approve an unscheduled-job suggestion in Week Ahead (that opens Calendar; you still pick the slot)\n- AI Receptionist booking, when Agent booking is on and the book step succeeds\n\nSetting a date alone when you create a job may not create a calendar block. If you do not see it on the week grid, it is usually still unscheduled. See Why isn’t this job on the calendar?',
  },
  {
    id: 'calendar-reschedule',
    q: 'How do I reschedule a job?',
    group: 'Scheduling jobs',
    keywords: ['reschedule', 'reschedule job', 'drag', 'move booking'],
    a: 'On Calendar, drag the existing block to a new slot. That is the reliable way to move a time today.\n\nThe Reschedule control on the calendar job detail is not a complete editor yet. The job page also does not have a full schedule editor.\n\nIf you need a different day, change week on Calendar and drag the block, or schedule again from the unscheduled queue if the job has no start time.',
  },
  {
    id: 'calendar-cancel',
    q: 'What happens when I cancel a scheduled job?',
    group: 'Scheduling jobs',
    keywords: ['cancel booking', 'cancel job', 'cancelled'],
    a: 'Cancelling a job changes its pipeline stage to Cancelled. It does not always clear the diary.\n\nAt the moment, a cancelled job can keep its scheduled time and still show on Calendar. If Google Calendar is connected, the copied event may also stay there.\n\nDo not treat cancel as “wipe this booking everywhere.” If the block is still in the week view, move or ignore it there. Reopening a cancelled job puts the job back on the board - it does not tidy leftover times or Google copies. See Can I reactivate cancelled jobs?',
  },
  {
    id: 'calendar-job-missing',
    q: 'Why isn’t this job on the calendar?',
    group: 'Scheduling jobs',
    keywords: ['missing job', 'not on calendar', 'date only'],
    a: 'Common reasons:\n- It has no scheduled start time (date-only or “sometime this week” is not enough)\n- You are looking at a different week than the booked time\n- Search or the week range is hiding it\n- The browser’s idea of “this week” does not match the business timezone\n- It is cancelled - at the moment it may still appear, but it can also be easy to overlook\n\nOpen the job and check whether a start time exists. If not, use Schedule Job or the unscheduled queue.',
  },
  {
    id: 'job-photos',
    q: 'Can I upload job photos?',
    group: 'Scheduling jobs',
    keywords: ['job photos', 'photos'],
    a: 'Yes. Job completion photo proof is included on the job.',
  },
  {
    id: 'prove-completion',
    q: 'Can I prove the job was completed?',
    group: 'Scheduling jobs',
    keywords: ['completion', 'proof'],
    a: 'Yes. Completion photos give you a record of the work performed.',
  },
  {
    id: 'calendar-availability',
    q: 'How does availability work?',
    group: 'Availability',
    keywords: ['availability', 'slots', 'free time'],
    a: 'When Agent booking checks times, StitchedUp looks at:\n- your AI booking hours (per day)\n- existing scheduled StitchedUp jobs that are not cancelled\n- the requested length (or the default length)\n- 30-minute slots\n- for today, times that are still in the future\n\nTimes use the business timezone. Google events, staff personal diaries, public holidays, and travel buffers are not used to block slots.\n\nOffering a slot is not the same as locking it. See Can two bookings use the same slot?',
  },
  {
    id: 'calendar-booking-hours',
    q: 'What are AI booking hours?',
    group: 'Availability',
    keywords: ['booking hours', 'ai booking hours', 'business hours'],
    a: 'AI booking hours are the per-day windows where the receptionist is allowed to offer times (for example Monday 8:00-16:00, Sunday off).\n\nThey are not the same as general knowledge hours you type for the AI to talk about, and they are not Google Calendar working hours.\n\nIf a day has no window, the AI will not book that day. Set these under AI Receptionist behaviour when Agent booking is on. See AI Receptionist Help for going live.',
  },
  {
    id: 'calendar-double-booking',
    q: 'Can two bookings use the same slot?',
    group: 'Availability',
    keywords: ['double booking', 'overlap', 'same slot'],
    a: 'Yes, in an edge case.\n\nStitchedUp checks availability before offering times, but the current booking flow does not perform a final overlap lock at the moment. Two bookings can land on the same slot if they are confirmed close together.\n\nIf that happens, move one job on Calendar (drag the block) and talk to the customer. Google events do not cause or prevent this.',
  },
  {
    id: 'calendar-ai-booking',
    q: 'How does the AI Receptionist book a job?',
    group: 'AI booking',
    keywords: ['ai booking', 'book job', 'receptionist booking'],
    a: 'When Agent booking is on, the AI checks StitchedUp availability, offers a slot, then must successfully create the booking in StitchedUp before it should say you are booked.\n\nThat creates (or reuses) a customer and a scheduled job. Copying the job to Google Calendar, if connected, is secondary and does not have to succeed for the booking to stand.\n\nThe AI does not use holidays, travel time, or each staff member’s diary. Full receptionist setup lives under AI Receptionist.',
  },
  {
    id: 'calendar-ai-google',
    q: 'Does AI booking need Google Calendar?',
    group: 'AI booking',
    keywords: ['ai booking', 'google calendar', 'need google'],
    a: 'No. The AI books against StitchedUp Calendar and your booking hours. Google Calendar is optional export after the job exists.\n\nYou can take AI bookings with Google disconnected.',
  },
  {
    id: 'calendar-ai-sync-failure',
    q: 'What if Google sync fails during AI booking?',
    group: 'AI booking',
    keywords: ['google sync', 'sync fail', 'ai booking'],
    a: 'The StitchedUp booking can still succeed. A Google copy problem does not undo the job.\n\nCheck Calendar in StitchedUp first. Reconnect Google under Settings → Integrations if you still want the export. See What if Google Calendar sync fails?',
  },
  {
    id: 'google-calendar',
    q: 'Does it sync with Google Calendar?',
    group: 'Google Calendar',
    keywords: ['google calendar', 'google calendar sync', 'one-way calendar sync'],
    a: 'Jobs can copy out to your primary Google calendar after they exist in StitchedUp. That is one-way (StitchedUp → Google). There is no Google → StitchedUp write path.\n\nStitchedUp Calendar is the source of truth. Google does not replace it. See Getting Started - Does Google Calendar replace StitchedUp Calendar?',
  },
  {
    id: 'calendar-google-connect',
    q: 'How do I connect Google Calendar?',
    group: 'Google Calendar',
    keywords: ['connect google', 'google calendar', 'integrations'],
    a: 'Go to Settings → Integrations and connect Google Calendar. Sign in with the Google account whose primary calendar should receive the copies.\n\nThis is optional. Connecting Google is a Setup Guide item; you do not need it to schedule in StitchedUp or to take AI bookings.',
  },
  {
    id: 'calendar-google-sync',
    q: 'What syncs to Google Calendar?',
    group: 'Google Calendar',
    keywords: ['what syncs', 'google calendar sync', 'primary calendar'],
    a: 'Scheduled StitchedUp jobs can appear on the connected primary Google calendar. Updates you make in StitchedUp may update that copy later.\n\nGoogle does not send events back. Customer or staff events that only exist in Google do not become StitchedUp jobs and do not block availability.',
  },
  {
    id: 'calendar-google-two-way',
    q: 'Is Google Calendar two-way?',
    group: 'Google Calendar',
    keywords: ['two-way', 'two way', 'bidirectional'],
    a: 'No. Sync is StitchedUp → Google only. Changes in Google do not update StitchedUp.',
  },
  {
    id: 'calendar-google-edit-delete',
    q: 'What happens if I edit or delete the Google event?',
    group: 'Google Calendar',
    keywords: ['delete google event', 'edit google event'],
    a: 'The StitchedUp job does not change. Availability and the week grid still follow StitchedUp.\n\nA later update in StitchedUp may overwrite, recreate, or refresh the Google copy depending on how that job is mapped. Always change times in StitchedUp Calendar, not in Google.',
  },
  {
    id: 'calendar-google-disconnect',
    q: 'What happens if I disconnect Google Calendar?',
    group: 'Google Calendar',
    keywords: ['disconnect google', 'turn off sync'],
    a: 'StitchedUp scheduling and AI booking continue. Disconnecting Google does not stop bookings.\n\nEvents already copied to Google stay there unless you delete them in Google yourself. New jobs will not copy out until you reconnect.',
  },
  {
    id: 'calendar-google-failure',
    q: 'What if Google Calendar sync fails?',
    group: 'Google Calendar',
    keywords: ['sync fails', 'google calendar sync', 'reconnect'],
    a: 'The StitchedUp booking remains authoritative. The Google copy may be missing or out of date.\n\nReconnect or check the connection under Settings → Integrations. Fix times in StitchedUp first. At the moment, cancelled or unscheduled jobs can also leave a stale Google event behind.',
  },
  {
    id: 'team-jobs',
    q: 'Who can see the calendar?',
    group: 'Team schedules',
    keywords: ['team calendar', 'who can see', 'permissions'],
    a: 'Tradespeople and apprentices only see jobs assigned to them on Jobs and Calendar.\n\nOwners, Office / VA, and Managers who can open Jobs and Calendar see business-wide jobs.\n\nAccountants do not use Calendar. Quotes-only and Social-only are limited product modes, not staff roles - those logins do not use Calendar as part of their usual work.\n\nSee Team & Permissions. Assigning a worker is still separate from putting a time on the calendar.',
  },
  {
    id: 'calendar-assignment',
    q: 'How does assignment relate to the calendar?',
    group: 'Team schedules',
    keywords: ['assign job', 'assignment', 'unassigned'],
    a: 'Assigning a worker does not schedule the job. Scheduling a time does not assign a worker. You may need both.\n\nAn assigned job with no start time stays in the unscheduled queue. A timed job with nobody assigned still shows as a block.',
  },
  {
    id: 'calendar-unscheduled',
    q: 'What is an unscheduled job?',
    group: 'Team schedules',
    keywords: ['unscheduled', 'unscheduled job', 'no start time'],
    a: 'The job exists - it can have a stage, an assigned person, notes, and even a preferred date - but it has no scheduled start time, so it does not get a block on the week grid.\n\nFind these in the Calendar unscheduled queue, or as Unscheduled jobs suggestions in Week Ahead. Approving a suggestion opens Calendar; it does not pick the slot for you.',
  },
  {
    id: 'calendar-todays-schedule',
    q: 'What is Today’s Schedule?',
    group: 'Dashboard views',
    keywords: ["today's schedule", 'todays schedule', 'today schedule', 'dashboard'],
    a: 'Today’s Schedule is a dashboard summary of jobs for the current day. It is not the full pipeline and not the full Calendar week.\n\nUse it as a quick list, then open the job or Calendar for the real booking. Do not treat it as a perfect timezone clock - “today” on the dashboard can differ slightly from the week grid if timezones disagree.\n\nCancelled or unscheduled work may not belong here even if the job still exists.',
  },
  {
    id: 'calendar-week-ahead',
    q: 'What is Week Ahead?',
    group: 'Dashboard views',
    keywords: ['week ahead', 'suggestions', 'schedule board'],
    a: 'Week Ahead is three related things:\n- The schedule board on Week Ahead - this week’s scheduled jobs\n- The AI suggestions inbox - unscheduled jobs, follow-up SMS, and social drafts waiting for your approval\n- The dashboard Week Ahead card - a count of suggestions, not a list of this week’s bookings\n\nNothing in the inbox sends or books until you approve it. Approving an unscheduled job opens Calendar. See Your Week Ahead for SMS and social suggestion rules.',
  },
  {
    id: 'calendar-track-arrival',
    q: 'How does Track My Arrival relate to the calendar?',
    group: 'Track My Arrival',
    keywords: ['track my arrival', 'on my way', 'eta'],
    a: 'The scheduled start is the appointment time on Calendar. Track My Arrival is separate: you tap On my way so the customer can see live travel and an ETA.\n\nIt does not start automatically at the booked time. The job still needs a start time, a site address, a customer phone, and the feature enabled in Settings.\n\nSee Track My Arrival for SMS, the customer page, and when sharing stops.',
  },
  {
    id: 'calendar-timezones',
    q: 'How do timezones work?',
    group: 'Troubleshooting',
    keywords: ['timezone', 'time zone', 'business timezone'],
    a: 'The business timezone (Settings → Business Profile) drives most scheduling and AI booking.\n\nThe week grid and “today” on a phone can still follow the browser’s local day. Google copies currently have timezone limits - if you change the business timezone, older Google events may look wrong even when StitchedUp is right.\n\nIf a job seems to sit on the wrong day, check the business timezone and which week you have open, then edit the time in StitchedUp.',
  },
  {
    id: 'calendar-common-mistakes',
    q: 'What are common scheduling mistakes?',
    group: 'Troubleshooting',
    keywords: ['mistakes', 'wrong calendar', 'double booking'],
    a: 'Watch for these:\n- Treating Google Calendar as the master diary\n- Editing or deleting the Google event instead of the StitchedUp job\n- Confusing job stage with “is this booked?”\n- Assigning someone and assuming they are scheduled\n- Scheduling a time and assuming someone is assigned\n- Expecting a date-only new job to appear on the week grid\n- Expecting the AI to read Google, staff diaries, or holidays\n- Disconnecting Google and thinking bookings stop\n- Expecting cancel to always clear Calendar and Google\n- Treating the Week Ahead dashboard card as this week’s schedule\n- Expecting Track My Arrival to start at the appointment time',
  },
  {
    id: 'reactivate-jobs',
    q: 'Can I reactivate cancelled jobs?',
    group: 'Troubleshooting',
    keywords: ['reactivate', 'reopen', 'cancelled'],
    a: 'Yes. Cancelled applies to the job, not the customer. Reopening a cancelled job puts that job back on the board (it returns to New Lead). The customer record was never closed or lost.\n\nReopening does not guarantee the old calendar time or Google copy is cleaned up. Check Calendar after you reopen, and set a new start time if you need one.',
  },
]

export const JOBS_SCHEDULING_HELP_QUESTION_IDS = QUESTIONS.map((question) => question.id)

export const JOBS_SCHEDULING_CATEGORY: HelpFaqCategory = {
  id: JOBS_SCHEDULING_HELP_CATEGORY_ID,
  title: 'Jobs & Scheduling',
  sidebarLabel: 'Jobs & Scheduling',
  description: 'StitchedUp Calendar, job times, availability, and Google export - separate from pipeline stages.',
  icon: Calendar,
  chipIds: ['jobs'],
  keywords: [
    'calendar',
    'job calendar',
    'schedule job',
    'reschedule job',
    'reschedule',
    'cancel booking',
    'unscheduled job',
    'unscheduled',
    'ai booking',
    'booking hours',
    'availability',
    'double booking',
    'google calendar sync',
    'one-way calendar sync',
    "today's schedule",
    'todays schedule',
    'week ahead',
    'track my arrival',
    'timezone',
  ],
  questions: QUESTIONS,
}

export const JOBS_SCHEDULING_HELP_ARTICLE_ALIASES: Record<string, string> = {
  'calendar-overview': 'jobs-scheduling-calendar-overview',
  'calendar-stage-vs-schedule': 'jobs-scheduling-calendar-stage-vs-schedule',
  'calendar-source-of-truth': 'jobs-scheduling-calendar-source-of-truth',
  'calendar-schedule-job': 'jobs-scheduling-schedule-jobs',
  'schedule-jobs': 'jobs-scheduling-schedule-jobs',
  'jobs-scheduling-calendar-schedule-job': 'jobs-scheduling-schedule-jobs',
  'calendar-reschedule': 'jobs-scheduling-calendar-reschedule',
  'calendar-cancel': 'jobs-scheduling-calendar-cancel',
  'calendar-job-missing': 'jobs-scheduling-calendar-job-missing',
  'calendar-availability': 'jobs-scheduling-calendar-availability',
  'calendar-booking-hours': 'jobs-scheduling-calendar-booking-hours',
  'calendar-double-booking': 'jobs-scheduling-calendar-double-booking',
  'calendar-ai-booking': 'jobs-scheduling-calendar-ai-booking',
  'calendar-ai-google': 'jobs-scheduling-calendar-ai-google',
  'calendar-ai-sync-failure': 'jobs-scheduling-calendar-ai-sync-failure',
  'calendar-google-connect': 'jobs-scheduling-calendar-google-connect',
  'calendar-google-sync': 'jobs-scheduling-calendar-google-sync',
  'calendar-google-two-way': 'jobs-scheduling-calendar-google-two-way',
  'calendar-google-edit-delete': 'jobs-scheduling-calendar-google-edit-delete',
  'calendar-google-disconnect': 'jobs-scheduling-calendar-google-disconnect',
  'calendar-google-failure': 'jobs-scheduling-calendar-google-failure',
  'calendar-team-visibility': 'jobs-scheduling-team-jobs',
  'team-jobs': 'jobs-scheduling-team-jobs',
  'calendar-assignment': 'jobs-scheduling-calendar-assignment',
  'calendar-unscheduled': 'jobs-scheduling-calendar-unscheduled',
  'calendar-todays-schedule': 'jobs-scheduling-calendar-todays-schedule',
  'calendar-week-ahead': 'jobs-scheduling-calendar-week-ahead',
  'calendar-track-arrival': 'jobs-scheduling-calendar-track-arrival',
  'calendar-timezones': 'jobs-scheduling-calendar-timezones',
  'calendar-common-mistakes': 'jobs-scheduling-calendar-common-mistakes',
  'jobs-scheduling-google-calendar': 'jobs-scheduling-google-calendar',
  'reactivate-jobs': 'jobs-scheduling-reactivate-jobs',
}
