/** Reserved seller-subdomain labels — not claimable as Storefront.slug. */
export const RESERVED_VENDL_SUBDOMAINS = new Set([
  "www",
  "app",
  "admin",
  "api",
  "dashboard",
  "shop",
  "store",
  "support",
  "help",
  "status",
  "mail",
  "email",
  "smtp",
  "ftp",
  "cdn",
  "assets",
  "static",
  "media",
  "images",
  "img",
  "blog",
  "docs",
  "dev",
  "staging",
  "preview",
  "beta",
  "account",
  "accounts",
  "auth",
  "login",
  "signup",
  "register",
  "billing",
  "checkout",
  "payments",
  "pay",
  "webhook",
  "webhooks",
  "health",
  "system",
  "root",
  "vendl",
  "stallside",
  "demo",
  "www-demo",
]);

export function isReservedVendlSubdomain(label: string): boolean {
  return RESERVED_VENDL_SUBDOMAINS.has(label.trim().toLowerCase());
}
