-- Social kit schema (generated by tools/build-schema.mjs from StitchedUp migrations 001-247).
-- Apply to a NEW, EMPTY Supabase project. Server-side service-role access only:
-- RLS is enabled on every table with no policies, so anon/authenticated keys see nothing.
SET search_path = public;

-- Trigger functions

CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$function$;

CREATE OR REPLACE FUNCTION public.update_social_posts_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_social_week_plans_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_social_week_plan_items_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

-- Minimal customers (only first/last name are read by the social code)

CREATE TABLE public.customers (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    business_id uuid,
    first_name text,
    last_name text,
    created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- Tables, indexes, constraints, triggers

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET transaction_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.social_week_plan_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    plan_id uuid NOT NULL,
    business_id uuid NOT NULL,
    sort_order integer NOT NULL,
    target_date date NOT NULL,
    post_type text NOT NULL,
    subtype_id text,
    intent_chip text,
    topic text NOT NULL,
    user_brief text,
    job_id uuid,
    platforms jsonb DEFAULT '[]'::jsonb NOT NULL,
    caption text,
    status text DEFAULT 'planned'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generation_id uuid,
    generation_status text DEFAULT 'not_started'::text NOT NULL,
    generation_error text,
    variant_previews jsonb,
    generation_started_at timestamp with time zone,
    generation_completed_at timestamp with time zone,
    selected_variant_id uuid,
    review_status text DEFAULT 'needs_selection'::text NOT NULL,
    hybrid_render_id uuid,
    scheduled_social_post_id uuid,
    approved_at timestamp with time zone,
    skipped_at timestamp with time zone,
    variant_previews_previous jsonb,
    CONSTRAINT social_week_plan_items_generation_status_check CHECK ((generation_status = ANY (ARRAY['not_started'::text, 'queued'::text, 'generating'::text, 'generated'::text, 'failed'::text]))),
    CONSTRAINT social_week_plan_items_review_status_check CHECK ((review_status = ANY (ARRAY['needs_selection'::text, 'selected'::text, 'approved'::text, 'scheduled'::text, 'skipped'::text]))),
    CONSTRAINT social_week_plan_items_status_check CHECK ((status = 'planned'::text))
);

COMMENT ON TABLE public.social_week_plan_items IS 'Individual planned posts within a social_week_plans row.';

COMMENT ON COLUMN public.social_week_plan_items.generation_status IS 'Per-item AI Designed generation lifecycle (separate from item.status planned).';

COMMENT ON COLUMN public.social_week_plan_items.selected_variant_id IS 'UUID of chosen variant_previews[].id — selection is free, no regen.';

COMMENT ON COLUMN public.social_week_plan_items.review_status IS 'Production desk lifecycle: needs_selection → selected → approved → scheduled (or skipped).';

COMMENT ON COLUMN public.social_week_plan_items.hybrid_render_id IS 'Library row after passThroughVisual finalization (0 credits).';

COMMENT ON COLUMN public.social_week_plan_items.scheduled_social_post_id IS 'Immutable scheduled post snapshot; planner edits do not alter this row.';

COMMENT ON COLUMN public.social_week_plan_items.variant_previews_previous IS 'Previous variant set after Quick Change (one-level history V1).';

CREATE TABLE public.ai_image_scene_options (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    purpose text NOT NULL,
    scene_label text NOT NULL,
    scene_prompt_fragment text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);

COMMENT ON TABLE public.ai_image_scene_options IS 'Preset scene options for social post AI image generation (Step 4 guided flow).';

CREATE TABLE public.ai_usage_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    user_id uuid,
    feature text NOT NULL,
    provider text NOT NULL,
    model text,
    usage_type text NOT NULL,
    input_tokens bigint,
    output_tokens bigint,
    cached_input_tokens bigint,
    units numeric,
    unit_name text,
    request_id text,
    provider_request_id text,
    related_entity_type text,
    related_entity_id uuid,
    provider_cost_usd numeric,
    fx_rate_usd_to_aud numeric,
    provider_cost_aud numeric,
    customer_credits_charged numeric,
    customer_amount_aud numeric,
    status text NOT NULL,
    cost_quality text DEFAULT 'unknown'::text NOT NULL,
    is_refunded boolean DEFAULT false NOT NULL,
    is_test boolean DEFAULT false NOT NULL,
    pricing_version text,
    error_code text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_usage_events_cost_quality_chk CHECK ((cost_quality = ANY (ARRAY['actual'::text, 'estimated'::text, 'unknown'::text]))),
    CONSTRAINT ai_usage_events_status_chk CHECK ((status = ANY (ARRAY['success'::text, 'failed'::text, 'partial'::text, 'cancelled'::text])))
);

COMMENT ON TABLE public.ai_usage_events IS 'Provider AI COGS events snapshotted at call time. Not customer billing. Metering starts at migration deploy. Do not store prompts or PII.';

CREATE TABLE public.business_brand_assets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    asset_type text DEFAULT 'logo'::text NOT NULL,
    storage_path text NOT NULL,
    public_url text,
    display_name text NOT NULL,
    variant_type text DEFAULT 'other'::text NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT business_brand_assets_type_check CHECK ((asset_type = 'logo'::text)),
    CONSTRAINT business_brand_assets_variant_check CHECK ((variant_type = ANY (ARRAY['primary'::text, 'light'::text, 'dark'::text, 'icon'::text, 'horizontal'::text, 'stacked'::text, 'other'::text])))
);

COMMENT ON TABLE public.business_brand_assets IS 'Approved brand assets (logos). Exactly one logo per business is primary; businesses.logo_url mirrors that primary.';

CREATE TABLE public.businesses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text,
    logo_url text,
    abn text,
    licence_number text,
    address text,
    phone text,
    email text,
    website text,
    payment_threshold numeric DEFAULT 1000,
    bank_bsb text,
    bank_account text,
    bank_name text,
    google_review_link text,
    review_template text DEFAULT 'Hi {client_name}, thanks for choosing {business_name}! We''d love it if you could leave us a quick Google review — it really helps our small business. {review_link} Thanks, {tradie_name}'::text,
    callout_fee_enabled boolean DEFAULT false,
    callout_fee_amount numeric DEFAULT 0,
    gst_registered boolean DEFAULT true,
    terms_and_conditions text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    subscription_tier text,
    account_status text DEFAULT 'active'::text NOT NULL,
    admin_notes text,
    suspended_at timestamp with time zone,
    suspended_reason text,
    gmb_review_link text,
    review_request_email_subject text DEFAULT 'How did we go, {client_name}?'::text,
    review_request_email_template text,
    review_request_sms_template text,
    review_page_title text DEFAULT 'How did we do?'::text,
    review_page_message text DEFAULT 'Your feedback means the world to us.'::text,
    review_auto_send boolean DEFAULT false,
    stripe_account_id text,
    stripe_account_status text DEFAULT 'not_connected'::text,
    stripe_onboarding_completed boolean DEFAULT false,
    stripe_charges_enabled boolean DEFAULT false,
    stripe_payouts_enabled boolean DEFAULT false,
    milestone_require_approval boolean DEFAULT false,
    milestone_approval_hours integer DEFAULT 48,
    milestone_default_split text DEFAULT 'equal'::text,
    google_calendar_access_token text,
    google_calendar_refresh_token text,
    google_calendar_token_expires_at timestamp with time zone,
    google_calendar_id text,
    google_calendar_sync_enabled boolean DEFAULT false,
    google_calendar_last_synced_at timestamp with time zone,
    default_labour_rate numeric DEFAULT 85,
    default_admin_rate numeric DEFAULT 45,
    track_job_costing boolean DEFAULT true,
    materials_markup_default numeric DEFAULT 100,
    brand_color text DEFAULT '#FFD100'::text,
    brand_text_color text DEFAULT '#0A0A0A'::text,
    subscription_started_at timestamp with time zone,
    refund_eligible_until timestamp with time zone,
    subscription_status text DEFAULT 'pending'::text,
    monthly_price numeric,
    airwallex_subscription_id text,
    airwallex_customer_id text,
    latitude numeric,
    longitude numeric,
    suburb text,
    state text,
    facebook_page_id text,
    facebook_page_name text,
    facebook_access_token text,
    instagram_account_id text,
    instagram_username text,
    gmb_account_id text,
    gmb_location_id text,
    gmb_location_name text,
    gmb_access_token text,
    gmb_refresh_token text,
    linkedin_page_id text,
    linkedin_access_token text,
    social_overlay_style text DEFAULT 'bottom_bar'::text,
    social_default_platforms text[] DEFAULT ARRAY['instagram'::text, 'facebook'::text, 'gmb'::text],
    social_brand_voice text DEFAULT 'professional'::text,
    social_default_cta text DEFAULT 'Call us for a free quote'::text,
    social_hashtag_template text,
    social_auto_prompt boolean DEFAULT true,
    ai_agent_enabled boolean DEFAULT false,
    ai_agent_mode text DEFAULT 'always'::text,
    ai_agent_greeting text DEFAULT 'Hi! How can I help you today?'::text,
    ai_agent_business_hours jsonb,
    ai_agent_services text,
    ai_agent_pricing_notes text,
    ai_agent_tone text DEFAULT 'friendly'::text,
    ai_agent_max_call_minutes integer DEFAULT 10,
    ai_agent_silence_timeout_seconds integer DEFAULT 15,
    ai_agent_max_concurrent_sessions integer DEFAULT 5,
    ai_agent_recording_notice text DEFAULT 'This conversation may be recorded for quality and training purposes.'::text,
    vapi_assistant_id text,
    vapi_phone_number_id text,
    vapi_phone_number text,
    ai_widget_position text DEFAULT 'bottom-right'::text NOT NULL,
    ai_widget_bubble_color text,
    ai_widget_text_color text,
    ai_widget_icon_style text DEFAULT 'chat_icon'::text NOT NULL,
    ai_widget_custom_icon_url text,
    ai_widget_type text DEFAULT 'chat'::text NOT NULL,
    ai_widget_placement text DEFAULT 'floating'::text NOT NULL,
    ai_voice_provider text DEFAULT 'elevenlabs'::text NOT NULL,
    ai_voice_id text,
    ai_voice_label text,
    ai_voice_speed numeric DEFAULT 1.0 NOT NULL,
    ai_voice_cloning_enabled boolean DEFAULT false NOT NULL,
    ai_voice_is_cloned boolean DEFAULT false NOT NULL,
    ai_cloned_voice_id text,
    ai_cloned_voice_status text,
    ai_collect_fields jsonb,
    ai_backchanneling_enabled boolean DEFAULT true NOT NULL,
    ai_response_speed text DEFAULT 'normal'::text NOT NULL,
    ai_interruption_sensitivity text DEFAULT 'normal'::text NOT NULL,
    ai_agent_call_flow_instructions text,
    ai_noise_cancellation_mode text DEFAULT 'remove_noise'::text NOT NULL,
    ai_idle_reminder_enabled boolean DEFAULT true NOT NULL,
    ai_speech_normalization_enabled boolean DEFAULT true NOT NULL,
    ai_boosted_keywords text DEFAULT ''::text,
    twilio_subaccount_sid text,
    twilio_subaccount_auth_token text,
    twilio_address_sid text,
    postcode text,
    twilio_end_user_sid text,
    twilio_supporting_document_sid text,
    twilio_bundle_sid text,
    twilio_bundle_status text,
    twilio_bundle_failure_reason text,
    twilio_bundle_failure_reasons jsonb,
    ai_booking_enabled boolean DEFAULT false NOT NULL,
    ai_booking_hours jsonb DEFAULT '{"friday": {"end": "18:00", "start": "07:00"}, "monday": {"end": "18:00", "start": "07:00"}, "sunday": null, "tuesday": {"end": "18:00", "start": "07:00"}, "saturday": {"end": "14:00", "start": "07:00"}, "thursday": {"end": "18:00", "start": "07:00"}, "wednesday": {"end": "18:00", "start": "07:00"}}'::jsonb,
    timezone text DEFAULT 'Australia/Sydney'::text NOT NULL,
    airwallex_billing_customer_id text,
    subscription_monthly_price integer,
    social_font_family text DEFAULT 'Inter'::text,
    social_font_size text DEFAULT 'medium'::text,
    social_text_styles jsonb DEFAULT '{"tagline": {"color": null, "fontSize": 20, "fontFamily": "Inter"}, "headline": {"color": null, "fontSize": 42, "fontFamily": "Inter"}, "description": {"color": null, "fontSize": 22, "fontFamily": "Inter"}}'::jsonb,
    social_logo_corner text DEFAULT 'bottom-right'::text NOT NULL,
    social_compose_last_category text,
    social_compose_last_subtype text,
    expense_scan_allowance_monthly integer DEFAULT 100 NOT NULL,
    expense_scan_used_this_period integer DEFAULT 0 NOT NULL,
    expense_scan_period text,
    trial_start timestamp with time zone,
    trial_end timestamp with time zone,
    past_due_at timestamp with time zone,
    subscription_access_until timestamp with time zone,
    airwallex_payment_source_id text,
    arrival_tracking_enabled boolean DEFAULT false NOT NULL,
    push_notifications_enabled boolean DEFAULT true NOT NULL,
    gmb_token_expires_at timestamp with time zone,
    onboarding_completed_at timestamp with time zone,
    airwallex_tradiespost_billing_customer_id text,
    airwallex_tradiespost_customer_id text,
    acquisition_product text,
    stripe_account_type text,
    primary_trade_slug text,
    ai_receptionist_setup_status text DEFAULT 'not_started'::text NOT NULL,
    ai_receptionist_setup_step integer DEFAULT 0 NOT NULL,
    ai_receptionist_policy_draft jsonb,
    ai_receptionist_policy_published jsonb,
    ai_receptionist_knowledge_draft jsonb,
    ai_receptionist_knowledge_published jsonb,
    ai_receptionist_website_url text,
    ai_receptionist_last_scan_at timestamp with time zone,
    ai_receptionist_last_scan jsonb,
    ai_receptionist_published_at timestamp with time zone,
    ai_receptionist_draft_updated_at timestamp with time zone,
    app_access_scope text DEFAULT 'full'::text NOT NULL,
    missed_call_phone_mode text,
    existing_business_number text,
    missed_call_forwarding_status text DEFAULT 'not_configured'::text NOT NULL,
    missed_call_ai_enabled boolean DEFAULT false NOT NULL,
    missed_call_sms_followup_enabled boolean DEFAULT true NOT NULL,
    missed_call_sms_ai_enabled boolean DEFAULT true NOT NULL,
    missed_call_initial_sms_template text,
    missed_call_sms_cooldown_minutes integer DEFAULT 5 NOT NULL,
    missed_call_no_response_followup_enabled boolean DEFAULT false NOT NULL,
    missed_call_test_mode boolean DEFAULT false NOT NULL,
    ai_receptionist_live_enabled boolean DEFAULT false NOT NULL,
    missed_call_ack_audio_path text,
    missed_call_ack_audio_hash text,
    missed_call_ack_voice_id text,
    missed_call_ack_generated_at timestamp with time zone,
    missed_call_ack_message text,
    missed_call_ack_mode text DEFAULT 'ai_voice'::text,
    missed_call_ack_recording_path text,
    missed_call_ack_recording_hash text,
    missed_call_ack_recording_duration_seconds numeric,
    missed_call_ack_recorded_at timestamp with time zone,
    missed_call_sms_delay_seconds integer DEFAULT 30 NOT NULL,
    missed_call_ai_sms_auto_reply_enabled boolean DEFAULT false NOT NULL,
    missed_call_sms_mode text DEFAULT 'manual'::text NOT NULL,
    missed_call_no_response_followup_delay_minutes integer DEFAULT 15 NOT NULL,
    missed_call_no_response_followup_message text,
    app_access_scopes text[] DEFAULT '{}'::text[] NOT NULL,
    missed_call_onboarding_completed_at timestamp with time zone,
    notification_email text,
    included_phone_number_count integer DEFAULT 0 NOT NULL,
    included_number_source text DEFAULT 'none'::text NOT NULL,
    tiktok_open_id text,
    tiktok_display_name text,
    tiktok_avatar_url text,
    tiktok_access_token text,
    tiktok_refresh_token text,
    tiktok_token_expires_at timestamp with time zone,
    tiktok_refresh_expires_at timestamp with time zone,
    tiktok_scopes text,
    CONSTRAINT businesses_account_status_check CHECK ((account_status = ANY (ARRAY['active'::text, 'suspended'::text, 'cancelled'::text]))),
    CONSTRAINT businesses_acquisition_product_check CHECK (((acquisition_product IS NULL) OR (acquisition_product = ANY (ARRAY['tradiespost'::text, 'stitchedup'::text])))),
    CONSTRAINT businesses_ai_agent_mode_check CHECK ((ai_agent_mode = ANY (ARRAY['always'::text, 'backup_only'::text]))),
    CONSTRAINT businesses_ai_agent_tone_check CHECK ((ai_agent_tone = ANY (ARRAY['friendly'::text, 'professional'::text, 'casual'::text]))),
    CONSTRAINT businesses_ai_cloned_voice_status_check CHECK ((ai_cloned_voice_status = ANY (ARRAY['pending'::text, 'processing'::text, 'ready'::text, 'failed'::text]))),
    CONSTRAINT businesses_ai_interruption_sensitivity_check CHECK ((ai_interruption_sensitivity = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text]))),
    CONSTRAINT businesses_ai_noise_cancellation_mode_check CHECK ((ai_noise_cancellation_mode = ANY (ARRAY['off'::text, 'remove_noise'::text, 'remove_noise_and_speech'::text]))),
    CONSTRAINT businesses_ai_receptionist_setup_status_check CHECK ((ai_receptionist_setup_status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'ready_to_test'::text, 'published'::text]))),
    CONSTRAINT businesses_ai_receptionist_setup_step_check CHECK (((ai_receptionist_setup_step >= 0) AND (ai_receptionist_setup_step <= 9))),
    CONSTRAINT businesses_ai_response_speed_check CHECK ((ai_response_speed = ANY (ARRAY['relaxed'::text, 'normal'::text, 'quick'::text]))),
    CONSTRAINT businesses_ai_widget_icon_style_check CHECK ((ai_widget_icon_style = ANY (ARRAY['chat_icon'::text, 'logo'::text, 'custom'::text]))),
    CONSTRAINT businesses_ai_widget_placement_check CHECK ((ai_widget_placement = ANY (ARRAY['floating'::text, 'inline'::text]))),
    CONSTRAINT businesses_ai_widget_position_check CHECK ((ai_widget_position = ANY (ARRAY['bottom-right'::text, 'bottom-left'::text]))),
    CONSTRAINT businesses_ai_widget_type_check CHECK ((ai_widget_type = ANY (ARRAY['chat'::text, 'voice'::text, 'chat_voice'::text]))),
    CONSTRAINT businesses_app_access_scope_check CHECK ((app_access_scope = ANY (ARRAY['full'::text, 'quotes_only'::text, 'social_only'::text, 'communications_only'::text]))),
    CONSTRAINT businesses_app_access_scopes_check CHECK ((app_access_scopes <@ ARRAY['quotes_only'::text, 'social_only'::text, 'communications_only'::text])),
    CONSTRAINT businesses_included_number_source_check CHECK ((included_number_source = ANY (ARRAY['none'::text, 'communications_entry'::text, 'promo'::text, 'plan_pro'::text]))),
    CONSTRAINT businesses_included_phone_number_count_check CHECK ((included_phone_number_count >= 0)),
    CONSTRAINT businesses_missed_call_ack_mode_check CHECK ((missed_call_ack_mode = ANY (ARRAY['ai_voice'::text, 'recorded_voice'::text]))),
    CONSTRAINT businesses_missed_call_followup_delay_minutes_check CHECK (((missed_call_no_response_followup_delay_minutes >= 5) AND (missed_call_no_response_followup_delay_minutes <= 1440))),
    CONSTRAINT businesses_missed_call_forwarding_status_check CHECK ((missed_call_forwarding_status = ANY (ARRAY['not_configured'::text, 'pending'::text, 'verified'::text, 'failed'::text]))),
    CONSTRAINT businesses_missed_call_phone_mode_check CHECK (((missed_call_phone_mode IS NULL) OR (missed_call_phone_mode = ANY (ARRAY['existing_forward'::text, 'stitchedup_number'::text, 'demo'::text])))),
    CONSTRAINT businesses_missed_call_sms_cooldown_minutes_check CHECK (((missed_call_sms_cooldown_minutes >= 0) AND (missed_call_sms_cooldown_minutes <= 240))),
    CONSTRAINT businesses_missed_call_sms_delay_seconds_check CHECK (((missed_call_sms_delay_seconds >= 15) AND (missed_call_sms_delay_seconds <= 600))),
    CONSTRAINT businesses_missed_call_sms_mode_check CHECK ((missed_call_sms_mode = ANY (ARRAY['auto'::text, 'draft'::text, 'manual'::text]))),
    CONSTRAINT businesses_social_brand_voice_check CHECK ((social_brand_voice = ANY (ARRAY['professional'::text, 'casual'::text, 'punchy'::text]))),
    CONSTRAINT businesses_social_font_size_check CHECK ((social_font_size = ANY (ARRAY['small'::text, 'medium'::text, 'large'::text]))),
    CONSTRAINT businesses_social_logo_corner_check CHECK ((social_logo_corner = ANY (ARRAY['bottom-right'::text, 'bottom-left'::text, 'top-right'::text, 'top-left'::text]))),
    CONSTRAINT businesses_social_overlay_style_check CHECK ((social_overlay_style = ANY (ARRAY['bottom_bar'::text, 'corner'::text, 'top_banner'::text, 'minimal_tag'::text, 'frame'::text, 'none'::text]))),
    CONSTRAINT businesses_stripe_account_status_check CHECK ((stripe_account_status = ANY (ARRAY['not_connected'::text, 'pending'::text, 'active'::text, 'restricted'::text]))),
    CONSTRAINT businesses_stripe_account_type_check CHECK (((stripe_account_type IS NULL) OR (stripe_account_type = ANY (ARRAY['express'::text, 'standard'::text])))),
    CONSTRAINT businesses_subscription_status_check CHECK ((subscription_status = ANY (ARRAY['pending'::text, 'processing'::text, 'trialing'::text, 'trial_expired'::text, 'active'::text, 'past_due'::text, 'refunded'::text, 'cancelled'::text]))),
    CONSTRAINT businesses_subscription_tier_check CHECK (((subscription_tier IS NULL) OR (subscription_tier = ANY (ARRAY['core'::text, 'pro'::text]))))
);

COMMENT ON COLUMN public.businesses.subscription_tier IS 'StitchedUp commercial plan: core or pro.';

COMMENT ON COLUMN public.businesses.google_calendar_sync_enabled IS 'Whether to auto-sync jobs to Google Calendar';

COMMENT ON COLUMN public.businesses.brand_color IS 'Primary brand color used on quotes, invoices, emails (hex format)';

COMMENT ON COLUMN public.businesses.brand_text_color IS 'Text color for buttons/CTAs using brand color (auto-calculated)';

COMMENT ON COLUMN public.businesses.subscription_started_at IS 'When the business started their paid subscription';

COMMENT ON COLUMN public.businesses.refund_eligible_until IS '30 days after subscription_started_at - full refund available until this date';

COMMENT ON COLUMN public.businesses.subscription_status IS 'active = paying customer, refunded = got full refund, cancelled = stopped subscription';

COMMENT ON COLUMN public.businesses.monthly_price IS 'Monthly subscription price in dollars (197, 297, or 497)';

COMMENT ON COLUMN public.businesses.airwallex_subscription_id IS 'Airwallex subscription ID for reference';

COMMENT ON COLUMN public.businesses.airwallex_customer_id IS 'Airwallex customer ID for reference';

COMMENT ON COLUMN public.businesses.ai_booking_enabled IS 'When true, the AI receptionist can check availability and book jobs via Vapi tools.';

COMMENT ON COLUMN public.businesses.ai_booking_hours IS 'Working hours for AI booking availability — day keys with {start,end} HH:MM or null if closed.';

COMMENT ON COLUMN public.businesses.timezone IS 'IANA timezone for job scheduling and calendar display (e.g. Australia/Sydney).';

COMMENT ON COLUMN public.businesses.airwallex_billing_customer_id IS 'Airwallex Billing Customer ID (bcus_*) for subscription billing — separate from PA customer.';

COMMENT ON COLUMN public.businesses.subscription_monthly_price IS 'Monthly subscription price in cents (e.g. 29700 = $297/month AUD)';

COMMENT ON COLUMN public.businesses.social_logo_corner IS 'Default corner for logo compositing on AI Full Post images.';

COMMENT ON COLUMN public.businesses.social_compose_last_category IS 'Last PostCategoryId selected in /social Create Step 1 (default tab).';

COMMENT ON COLUMN public.businesses.social_compose_last_subtype IS 'Last PostSubtypeId selected in /social Create Step 1.';

COMMENT ON COLUMN public.businesses.trial_start IS 'When the 30-day card-free product trial began (post-onboarding).';

COMMENT ON COLUMN public.businesses.trial_end IS 'When trialing access ends if no paid subscription.';

COMMENT ON COLUMN public.businesses.past_due_at IS 'First transition to past_due — used for 14-day grace before lockout.';

COMMENT ON COLUMN public.businesses.subscription_access_until IS 'Paid access end (cancel-at-period-end or period end from Airwallex).';

COMMENT ON COLUMN public.businesses.airwallex_payment_source_id IS 'Latest Airwallex Payment Source (psrc_*) for card-on-file before subscription or synced from checkout.';

COMMENT ON COLUMN public.businesses.arrival_tracking_enabled IS 'Opt-in: tradies can send customers a short-lived on-my-way tracking link via SMS.';

COMMENT ON COLUMN public.businesses.push_notifications_enabled IS 'When false, server-side push sends are skipped for all users in this business.';

COMMENT ON COLUMN public.businesses.onboarding_completed_at IS 'When the owner finished or skipped the last onboarding wizard step. NULL = still required.';

COMMENT ON COLUMN public.businesses.airwallex_tradiespost_billing_customer_id IS 'Airwallex billing customer (bcus_*) on the TradiesPost Airwallex account (AIRWALLEX_TRADIESPOST_*).';

COMMENT ON COLUMN public.businesses.airwallex_tradiespost_customer_id IS 'Airwallex PA customer (cus_*) on the TradiesPost Airwallex account (AIRWALLEX_TRADIESPOST_*).';

COMMENT ON COLUMN public.businesses.acquisition_product IS 'Original product at signup (tradiespost | stitchedup). Set once; null for legacy rows.';

COMMENT ON COLUMN public.businesses.stripe_account_type IS 'express = new Connect account via Account Links; standard = existing Stripe account via OAuth';

COMMENT ON COLUMN public.businesses.primary_trade_slug IS 'Canonical primary trade for Trade Library, recommendations, and AI context.';

COMMENT ON COLUMN public.businesses.app_access_scope IS 'Preferred/home gated scope (last campaign). Use app_access_scopes for allowlist union.';

COMMENT ON COLUMN public.businesses.missed_call_phone_mode IS 'existing_forward = keep carrier number and forward misses; stitchedup_number = owned StitchedUp line; demo = trial on the shared platform demo number';

COMMENT ON COLUMN public.businesses.existing_business_number IS 'Tradie-owned mobile/business number (E.164 or local AU) used in existing_forward mode — not the Twilio messaging number';

COMMENT ON COLUMN public.businesses.ai_receptionist_live_enabled IS 'When true, inbound calls on the StitchedUp business number are answered by the AI voice receptionist (Vapi). Publish/setup status is independent.';

COMMENT ON COLUMN public.businesses.missed_call_ack_audio_path IS 'Storage object path in missed-call-ack bucket for the cached acknowledgement MP3.';

COMMENT ON COLUMN public.businesses.missed_call_ack_audio_hash IS 'Deterministic cache key (voice + copy + version). Skip ElevenLabs when unchanged.';

COMMENT ON COLUMN public.businesses.missed_call_ack_message IS 'Owner-edited missed-call voice acknowledgement. Null or empty uses the canonical default.';

COMMENT ON COLUMN public.businesses.missed_call_ack_mode IS 'ai_voice = generated receptionist clip; recorded_voice = owner-recorded WAV.';

COMMENT ON COLUMN public.businesses.app_access_scopes IS 'Stacked gated campaign scopes. Empty = full product. Prefer app_access_scope for home path.';

COMMENT ON COLUMN public.businesses.missed_call_onboarding_completed_at IS 'Set when the communications first-run missed-call wizard is finished.';

COMMENT ON COLUMN public.businesses.notification_email IS 'Optional Missed Call AI / lead alert destination. Does not change login email.';

COMMENT ON COLUMN public.businesses.included_phone_number_count IS 'Count of numbers whose Twilio rent is waived. Communications entry = 1. Never cleared on upgrade.';

COMMENT ON COLUMN public.businesses.tiktok_access_token IS 'TikTok user access token (24h). Refreshed via tiktok_refresh_token (365d, rotates).';

CREATE TABLE public.google_business_performance_daily (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    gmb_location_id text NOT NULL,
    metric_date date NOT NULL,
    business_impressions_desktop_maps integer,
    business_impressions_mobile_maps integer,
    business_impressions_desktop_search integer,
    business_impressions_mobile_search integer,
    website_clicks integer,
    call_clicks integer,
    business_direction_requests integer,
    business_conversations integer,
    business_bookings integer,
    business_food_orders integer,
    business_food_menu_clicks integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.google_business_performance_daily IS 'Cached GBP daily metrics from Business Profile Performance API. Cron writes via service_role.';

CREATE TABLE public.google_business_search_keywords (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    gmb_location_id text NOT NULL,
    month date NOT NULL,
    keyword text NOT NULL,
    impressions integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.google_business_search_keywords IS 'Cached GBP monthly search-keyword impressions. month is first-of-month.';

CREATE TABLE public.hybrid_social_renders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    job_id uuid,
    preset text NOT NULL,
    platform text NOT NULL,
    photo_source text,
    photo_url text,
    content jsonb DEFAULT '{}'::jsonb NOT NULL,
    result_url text,
    status text DEFAULT 'processing'::text NOT NULL,
    error_message text,
    used_free_trial boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT hybrid_social_renders_platform_check CHECK ((platform = ANY (ARRAY['instagram'::text, 'facebook'::text, 'gmb'::text]))),
    CONSTRAINT hybrid_social_renders_status_check CHECK ((status = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text])))
);

COMMENT ON TABLE public.hybrid_social_renders IS 'Hybrid social image renders (infographic/scene SVG+resvg) — charged via render_credits.';

CREATE TABLE public.job_photos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id uuid NOT NULL,
    business_id uuid NOT NULL,
    url text NOT NULL,
    webp_url text,
    file_size integer,
    stage_at_upload text,
    trade_type text,
    suburb text,
    caption text,
    uploaded_by uuid,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT job_photos_stage_at_upload_check CHECK ((stage_at_upload = ANY (ARRAY['in_progress'::text, 'job_done'::text, 'quote'::text])))
);

CREATE TABLE public.jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    customer_id uuid,
    title text NOT NULL,
    site_address text,
    stage text DEFAULT 'new_lead'::text NOT NULL,
    assigned_to uuid,
    callout_fee_applied boolean DEFAULT false,
    payment_path text,
    notes text,
    cancellation_reason text,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    payment_structure text DEFAULT 'single'::text,
    milestone_count integer DEFAULT 0,
    total_collected numeric DEFAULT 0,
    total_outstanding numeric DEFAULT 0,
    scheduled_start timestamp with time zone,
    scheduled_end timestamp with time zone,
    scheduled_date date,
    duration_hours numeric DEFAULT 1,
    calendar_color text,
    google_calendar_event_id text,
    is_recurring boolean DEFAULT false,
    recurring_frequency text,
    labour_rate_override numeric,
    labour_hours_actual numeric DEFAULT 0,
    materials_cost_actual numeric DEFAULT 0,
    subcontractor_cost numeric DEFAULT 0,
    other_cost numeric DEFAULT 0,
    total_revenue numeric DEFAULT 0,
    total_cost numeric DEFAULT 0,
    gross_profit numeric DEFAULT 0,
    gross_margin numeric DEFAULT 0,
    net_profit numeric DEFAULT 0,
    net_margin numeric DEFAULT 0,
    stripe_fees numeric DEFAULT 0,
    platform_fees numeric DEFAULT 0,
    costing_notes text,
    job_category text,
    site_latitude numeric,
    site_longitude numeric,
    site_suburb text,
    site_state text,
    site_postcode text,
    urgency text DEFAULT 'unknown'::text NOT NULL,
    emergency_callback_required boolean DEFAULT false NOT NULL,
    CONSTRAINT jobs_payment_path_check CHECK ((payment_path = ANY (ARRAY['stripe'::text, 'direct'::text, 'split'::text, 'milestone'::text]))),
    CONSTRAINT jobs_payment_structure_check CHECK ((payment_structure = ANY (ARRAY['single'::text, 'deposit'::text, 'milestone'::text]))),
    CONSTRAINT jobs_recurring_frequency_check CHECK ((recurring_frequency = ANY (ARRAY['weekly'::text, 'fortnightly'::text, 'monthly'::text]))),
    CONSTRAINT jobs_stage_check CHECK ((stage = ANY (ARRAY['new_lead'::text, 'contacted'::text, 'quote_sent'::text, 'quote_accepted'::text, 'in_progress'::text, 'job_done'::text, 'invoice_sent'::text, 'paid'::text, 'cancelled'::text]))),
    CONSTRAINT jobs_urgency_check CHECK ((urgency = ANY (ARRAY['emergency'::text, 'urgent'::text, 'normal'::text, 'unknown'::text])))
);

COMMENT ON COLUMN public.jobs.scheduled_start IS 'Start date and time of scheduled job (AEST)';

COMMENT ON COLUMN public.jobs.scheduled_end IS 'End date and time of scheduled job (AEST)';

COMMENT ON COLUMN public.jobs.scheduled_date IS 'Date portion of scheduled_start for easier querying';

COMMENT ON COLUMN public.jobs.duration_hours IS 'Duration in hours (e.g. 0.5 for 30min, 1.5 for 90min)';

COMMENT ON COLUMN public.jobs.google_calendar_event_id IS 'Google Calendar event ID for synced jobs';

COMMENT ON COLUMN public.jobs.urgency IS 'Call/chat urgency from AI structured data. emergency = live safety issue.';

COMMENT ON COLUMN public.jobs.emergency_callback_required IS 'True when urgent callback follow-up is required (e.g. failed emergency transfer).';

CREATE TABLE public.meta_connect_pending_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    user_id uuid NOT NULL,
    platform text NOT NULL,
    pages jsonb DEFAULT '[]'::jsonb NOT NULL,
    demo boolean DEFAULT false NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT meta_connect_pending_sessions_platform_check CHECK ((platform = ANY (ARRAY['facebook'::text, 'instagram'::text])))
);

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    user_id uuid,
    type text NOT NULL,
    title text NOT NULL,
    message text,
    read boolean DEFAULT false,
    job_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    reference_id text,
    url text
);

CREATE TABLE public.render_credit_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    event_type text NOT NULL,
    credits integer NOT NULL,
    render_id uuid,
    pack_key text,
    airwallex_ref text,
    amount_aud numeric(10,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT render_credit_events_event_type_check CHECK ((event_type = ANY (ARRAY['purchase'::text, 'used'::text, 'refund'::text]))),
    CONSTRAINT render_credit_events_pack_key_check CHECK (((pack_key IS NULL) OR (pack_key = ANY (ARRAY['10'::text, '25'::text, '60'::text]))))
);

COMMENT ON TABLE public.render_credit_events IS 'Ledger for render credit purchases, usage, and refunds.';

COMMENT ON COLUMN public.render_credit_events.render_id IS 'Optional correlation id (before_after_renders.id or hybrid_social_renders.id).';

CREATE TABLE public.render_credits (
    business_id uuid NOT NULL,
    credits_remaining integer DEFAULT 0 NOT NULL,
    free_trial_used boolean DEFAULT false NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT render_credits_credits_remaining_check CHECK ((credits_remaining >= 0))
);

COMMENT ON TABLE public.render_credits IS 'Before & After render credit balance per business — separate from subscription and social credits.';

CREATE TABLE public.social_credit_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event_type text DEFAULT 'image_generated'::text NOT NULL,
    template_style integer,
    post_type text,
    platform text,
    job_id uuid,
    orshot_template_id text DEFAULT '14154'::text,
    orshot_render_url text,
    credits_used integer DEFAULT 1 NOT NULL,
    cost_usd numeric(10,4) DEFAULT 0.01,
    is_test boolean DEFAULT false
);

COMMENT ON TABLE public.social_credit_events IS 'Orshot render credit log — one row per image_generated event.';

CREATE TABLE public.social_media_assets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    job_id uuid,
    media_type text DEFAULT 'video'::text NOT NULL,
    status text DEFAULT 'uploading'::text NOT NULL,
    original_url text,
    processed_url text,
    thumbnail_url text,
    storage_path text,
    thumbnail_path text,
    duration_seconds numeric,
    mime_type text,
    file_size_bytes bigint,
    caption text,
    about_text text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_storage_path text,
    processing_status text DEFAULT 'none'::text NOT NULL,
    branding_config jsonb,
    CONSTRAINT social_media_assets_media_type_check CHECK ((media_type = 'video'::text)),
    CONSTRAINT social_media_assets_processing_status_check CHECK ((processing_status = ANY (ARRAY['none'::text, 'processing'::text, 'processed'::text, 'processing_failed'::text]))),
    CONSTRAINT social_media_assets_status_check CHECK ((status = ANY (ARRAY['uploading'::text, 'ready'::text, 'failed'::text, 'deleted'::text])))
);

COMMENT ON TABLE public.social_media_assets IS 'Customer-uploaded social media (video V1). Generated images remain in hybrid_social_renders.';

COMMENT ON COLUMN public.social_media_assets.processed_storage_path IS 'Storage path for branded MP4 output (social-posts bucket). Original storage_path unchanged.';

COMMENT ON COLUMN public.social_media_assets.processing_status IS 'Branding pipeline state — separate from upload status (uploading/ready/failed/deleted).';

COMMENT ON COLUMN public.social_media_assets.branding_config IS 'Last successful branding settings (logo, positions, overlay text) for edit/reprocess UX.';

CREATE TABLE public.social_posts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    job_id uuid,
    status text DEFAULT 'draft'::text NOT NULL,
    caption text,
    platforms text[] DEFAULT ARRAY['instagram'::text] NOT NULL,
    photo_urls text[],
    processed_photo_urls jsonb,
    scheduled_for timestamp with time zone,
    posted_at timestamp with time zone,
    facebook_post_id text,
    instagram_post_id text,
    gmb_post_id text,
    linkedin_post_id text,
    facebook_error text,
    instagram_error text,
    gmb_error text,
    linkedin_error text,
    job_suburb text,
    job_state text,
    trade_type text,
    ai_generated boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    media_type text DEFAULT 'image'::text,
    video_url text,
    video_duration_seconds numeric,
    uploaded_media_urls text[],
    overlay_style_override text,
    platform_captions jsonb DEFAULT '{}'::jsonb,
    posted_manually boolean DEFAULT false NOT NULL,
    compose_category text,
    compose_subtype text,
    publishing_mode text DEFAULT 'automatic'::text NOT NULL,
    week_plan_item_id uuid,
    tiktok_publish_id text,
    tiktok_post_id text,
    tiktok_error text,
    tiktok_status text,
    tiktok_settings jsonb,
    CONSTRAINT social_posts_media_type_check CHECK ((media_type = ANY (ARRAY['image'::text, 'video'::text, 'carousel'::text]))),
    CONSTRAINT social_posts_overlay_style_override_check CHECK ((overlay_style_override = ANY (ARRAY['bottom_bar'::text, 'corner'::text, 'top_banner'::text, 'minimal_tag'::text, 'frame'::text, 'none'::text]))),
    CONSTRAINT social_posts_publishing_mode_check CHECK ((publishing_mode = ANY (ARRAY['automatic'::text, 'manual'::text]))),
    CONSTRAINT social_posts_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'posted'::text, 'failed'::text, 'cancelled'::text])))
);

COMMENT ON COLUMN public.social_posts.media_type IS 'image | video | carousel';

COMMENT ON COLUMN public.social_posts.video_url IS 'Direct URL to video file in Supabase storage';

COMMENT ON COLUMN public.social_posts.video_duration_seconds IS 'Validated duration in seconds (max 30)';

COMMENT ON COLUMN public.social_posts.uploaded_media_urls IS 'Media uploaded directly (not from job photos)';

COMMENT ON COLUMN public.social_posts.platform_captions IS 'Per-platform caption map, e.g. {"instagram":"...","facebook":"...","gmb":"..."}. Legacy caption column remains fallback until Stage 2/3.';

COMMENT ON COLUMN public.social_posts.posted_manually IS 'True when the tradie marked the post as published manually (no platform API call).';

COMMENT ON COLUMN public.social_posts.compose_category IS 'Optional PostCategoryId when post was created from template compose.';

COMMENT ON COLUMN public.social_posts.compose_subtype IS 'Optional PostSubtypeId when post was created from template compose.';

COMMENT ON COLUMN public.social_posts.publishing_mode IS 'automatic = cron/API publish; manual = calendar reminder only, never auto-published.';

COMMENT ON COLUMN public.social_posts.week_plan_item_id IS 'Planner item that created this calendar row; survives planner reset for history lookup.';

COMMENT ON COLUMN public.social_posts.tiktok_status IS 'Last TikTok publish status: PROCESSING_UPLOAD | PROCESSING_DOWNLOAD | SEND_TO_USER_INBOX | PUBLISH_COMPLETE | FAILED';

COMMENT ON COLUMN public.social_posts.tiktok_settings IS 'User-chosen TikTok post settings: { privacyLevel, disableComment, disableDuet, disableStitch, brandOrganic, brandedContent }';

CREATE TABLE public.social_style_templates (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    trade_category text NOT NULL,
    orshot_template_id text NOT NULL,
    orshot_page numeric,
    thumbnail_url text,
    sort_order integer DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    fields jsonb DEFAULT '[{"key": "headline", "type": "text", "label": "Business name", "source": "businessName", "maxLength": 60}, {"key": "description", "type": "text", "label": "Description", "source": "jobDescription", "maxLength": 120}, {"key": "tagline", "type": "text", "label": "Tagline", "source": "tagline", "maxLength": 50}, {"key": "website", "type": "text", "label": "Website", "source": "website"}, {"key": "social", "type": "text", "label": "Social handle", "source": "socialHandle"}, {"key": "service1", "type": "text", "label": "Service 1", "maxLength": 40}, {"key": "service2", "type": "text", "label": "Service 2", "maxLength": 40}, {"key": "phone", "type": "text", "label": "Phone", "source": "businessPhone"}, {"key": "photo", "type": "photo", "label": "Photo"}]'::jsonb
);

COMMENT ON TABLE public.social_style_templates IS 'Orshot social post style library — trade_category filters Step 3 tabs.';

CREATE TABLE public.social_video_processing_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    asset_id uuid NOT NULL,
    business_id uuid NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    logo_choice text DEFAULT 'none'::text NOT NULL,
    logo_asset_id uuid,
    logo_position text,
    logo_size text,
    overlay_text text,
    text_position text,
    output_storage_path text NOT NULL,
    output_version integer DEFAULT 1 NOT NULL,
    previous_processed_path text,
    error_code text,
    error_message text,
    claimed_at timestamp with time zone,
    worker_id text,
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT social_video_processing_jobs_logo_choice_check CHECK ((logo_choice = ANY (ARRAY['none'::text, 'primary'::text, 'asset'::text]))),
    CONSTRAINT social_video_processing_jobs_logo_position_check CHECK (((logo_position IS NULL) OR (logo_position = ANY (ARRAY['top_left'::text, 'top_right'::text, 'bottom_left'::text, 'bottom_right'::text])))),
    CONSTRAINT social_video_processing_jobs_logo_size_check CHECK (((logo_size IS NULL) OR (logo_size = ANY (ARRAY['small'::text, 'medium'::text, 'large'::text])))),
    CONSTRAINT social_video_processing_jobs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text]))),
    CONSTRAINT social_video_processing_jobs_text_position_check CHECK (((text_position IS NULL) OR (text_position = ANY (ARRAY['top'::text, 'center'::text, 'bottom'::text]))))
);

COMMENT ON TABLE public.social_video_processing_jobs IS 'Async queue for FFmpeg video branding. Worker claims pending rows via service role.';

CREATE TABLE public.social_week_plans (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    week_start_date date NOT NULL,
    status text DEFAULT 'draft'::text NOT NULL,
    post_count_target integer NOT NULL,
    wizard_answers jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by_user_id uuid,
    approved_by_user_id uuid,
    approved_at timestamp with time zone,
    generation_started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generation_status text DEFAULT 'not_started'::text NOT NULL,
    CONSTRAINT social_week_plans_generation_status_check CHECK ((generation_status = ANY (ARRAY['not_started'::text, 'queued'::text, 'generating'::text, 'ready'::text, 'partial_failed'::text, 'failed'::text]))),
    CONSTRAINT social_week_plans_post_count_target_check CHECK (((post_count_target >= 1) AND (post_count_target <= 7))),
    CONSTRAINT social_week_plans_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'plan_approved'::text, 'archived'::text])))
);

COMMENT ON TABLE public.social_week_plans IS 'Build My Week — weekly social content plans (Phase A: text-only, no image generation).';

COMMENT ON COLUMN public.social_week_plans.generation_status IS 'Async whole-week generation lifecycle (separate from plan.status).';

CREATE TABLE public.users (
    id uuid NOT NULL,
    business_id uuid,
    email text NOT NULL,
    full_name text,
    phone text,
    role text NOT NULL,
    permissions jsonb DEFAULT '{"can_view_crm": false, "can_send_quotes": false, "can_mark_job_done": false, "can_send_invoices": false, "can_upload_photos": false}'::jsonb,
    avatar_url text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    admin_product_access text[] DEFAULT '{}'::text[] NOT NULL,
    internal_staff_status text,
    CONSTRAINT users_internal_staff_status_check CHECK (((internal_staff_status IS NULL) OR (internal_staff_status = ANY (ARRAY['pending'::text, 'active'::text, 'disabled'::text])))),
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['super_admin'::text, 'support_admin'::text, 'owner'::text, 'team_member'::text, 'va'::text, 'accountant'::text])))
);

COMMENT ON COLUMN public.users.admin_product_access IS 'Platform staff product scope: stitchedup, tradiespost. Empty for customer users. super_admin ignores (full access).';

COMMENT ON COLUMN public.users.internal_staff_status IS 'Internal staff lifecycle: pending (pre-accept), active, disabled. NULL for customer users.';

CREATE TABLE public.webhook_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid,
    source text DEFAULT 'native'::text NOT NULL,
    event_type text NOT NULL,
    status text DEFAULT 'success'::text NOT NULL,
    payload jsonb,
    error_message text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT webhook_logs_status_check CHECK ((status = ANY (ARRAY['success'::text, 'error'::text])))
);

COMMENT ON TABLE public.webhook_logs IS 'Raw third-party webhook payloads (may contain call transcripts + customer PII). RLS enabled with no policies — service-role only.';

ALTER TABLE ONLY public.ai_image_scene_options
    ADD CONSTRAINT ai_image_scene_options_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_usage_events
    ADD CONSTRAINT ai_usage_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.business_brand_assets
    ADD CONSTRAINT business_brand_assets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.businesses
    ADD CONSTRAINT businesses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.google_business_performance_daily
    ADD CONSTRAINT google_business_performance_d_business_id_gmb_location_id_m_key UNIQUE (business_id, gmb_location_id, metric_date);

ALTER TABLE ONLY public.google_business_performance_daily
    ADD CONSTRAINT google_business_performance_daily_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.google_business_search_keywords
    ADD CONSTRAINT google_business_search_keywor_business_id_gmb_location_id_m_key UNIQUE (business_id, gmb_location_id, month, keyword);

ALTER TABLE ONLY public.google_business_search_keywords
    ADD CONSTRAINT google_business_search_keywords_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.hybrid_social_renders
    ADD CONSTRAINT hybrid_social_renders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.job_photos
    ADD CONSTRAINT job_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.meta_connect_pending_sessions
    ADD CONSTRAINT meta_connect_pending_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.render_credit_events
    ADD CONSTRAINT render_credit_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.render_credits
    ADD CONSTRAINT render_credits_pkey PRIMARY KEY (business_id);

ALTER TABLE ONLY public.social_credit_events
    ADD CONSTRAINT social_credit_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.social_media_assets
    ADD CONSTRAINT social_media_assets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.social_posts
    ADD CONSTRAINT social_posts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.social_style_templates
    ADD CONSTRAINT social_style_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.social_video_processing_jobs
    ADD CONSTRAINT social_video_processing_jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.social_week_plan_items
    ADD CONSTRAINT social_week_plan_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.social_week_plans
    ADD CONSTRAINT social_week_plans_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.webhook_logs
    ADD CONSTRAINT webhook_logs_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX business_brand_assets_one_primary ON public.business_brand_assets USING btree (business_id) WHERE (is_primary AND (asset_type = 'logo'::text));

CREATE INDEX businesses_primary_trade_slug_idx ON public.businesses USING btree (primary_trade_slug) WHERE (primary_trade_slug IS NOT NULL);

CREATE INDEX businesses_refund_eligible_idx ON public.businesses USING btree (refund_eligible_until) WHERE (refund_eligible_until IS NOT NULL);

CREATE INDEX businesses_subscription_status_idx ON public.businesses USING btree (subscription_status) WHERE (subscription_status IS NOT NULL);

CREATE INDEX idx_ai_image_scene_options_purpose ON public.ai_image_scene_options USING btree (purpose, sort_order);

CREATE INDEX idx_ai_usage_events_business_created ON public.ai_usage_events USING btree (business_id, created_at DESC);

CREATE INDEX idx_ai_usage_events_feature_created ON public.ai_usage_events USING btree (feature, created_at DESC);

CREATE INDEX idx_ai_usage_events_provider_model_created ON public.ai_usage_events USING btree (provider, model, created_at DESC);

CREATE UNIQUE INDEX idx_ai_usage_events_provider_request ON public.ai_usage_events USING btree (provider, provider_request_id, usage_type) WHERE (provider_request_id IS NOT NULL);

CREATE INDEX idx_ai_usage_events_related ON public.ai_usage_events USING btree (related_entity_type, related_entity_id) WHERE (related_entity_id IS NOT NULL);

CREATE INDEX idx_business_brand_assets_business ON public.business_brand_assets USING btree (business_id, created_at);

CREATE INDEX idx_businesses_onboarding_incomplete ON public.businesses USING btree (id) WHERE (onboarding_completed_at IS NULL);

CREATE INDEX idx_businesses_trialing_trial_end ON public.businesses USING btree (trial_end) WHERE (subscription_status = 'trialing'::text);

CREATE INDEX idx_gbp_perf_daily_business_date ON public.google_business_performance_daily USING btree (business_id, metric_date DESC);

CREATE INDEX idx_gbp_search_keywords_business_month ON public.google_business_search_keywords USING btree (business_id, month DESC);

CREATE INDEX idx_hybrid_social_renders_business ON public.hybrid_social_renders USING btree (business_id, created_at DESC);

CREATE UNIQUE INDEX idx_render_credit_events_airwallex_purchase ON public.render_credit_events USING btree (airwallex_ref) WHERE ((airwallex_ref IS NOT NULL) AND (event_type = 'purchase'::text));

CREATE INDEX idx_render_credit_events_business ON public.render_credit_events USING btree (business_id, created_at DESC);

CREATE INDEX idx_social_credit_events_business ON public.social_credit_events USING btree (business_id, created_at DESC);

CREATE INDEX idx_social_media_assets_business ON public.social_media_assets USING btree (business_id, created_at DESC);

CREATE INDEX idx_social_media_assets_job ON public.social_media_assets USING btree (job_id) WHERE (job_id IS NOT NULL);

CREATE INDEX idx_social_media_assets_processing ON public.social_media_assets USING btree (business_id, processing_status) WHERE (processing_status = ANY (ARRAY['processing'::text, 'processing_failed'::text]));

CREATE INDEX idx_social_media_assets_uploading ON public.social_media_assets USING btree (created_at) WHERE (status = 'uploading'::text);

CREATE INDEX idx_social_posts_automatic_due ON public.social_posts USING btree (scheduled_for) WHERE ((status = 'scheduled'::text) AND (publishing_mode = 'automatic'::text));

CREATE INDEX idx_social_posts_business_status ON public.social_posts USING btree (business_id, status);

CREATE INDEX idx_social_posts_job ON public.social_posts USING btree (job_id);

CREATE INDEX idx_social_posts_scheduled ON public.social_posts USING btree (scheduled_for) WHERE (status = 'scheduled'::text);

CREATE INDEX idx_social_posts_tiktok_pending ON public.social_posts USING btree (updated_at) WHERE ((tiktok_publish_id IS NOT NULL) AND (tiktok_post_id IS NULL) AND (tiktok_error IS NULL));

CREATE INDEX idx_social_posts_week_plan_item ON public.social_posts USING btree (week_plan_item_id) WHERE (week_plan_item_id IS NOT NULL);

CREATE UNIQUE INDEX idx_social_style_templates_orshot_page_unique ON public.social_style_templates USING btree (orshot_template_id, COALESCE(orshot_page, ('-1'::integer)::numeric)) WHERE (is_active = true);

CREATE INDEX idx_social_style_templates_trade ON public.social_style_templates USING btree (trade_category, sort_order) WHERE (is_active = true);

CREATE UNIQUE INDEX idx_social_video_one_active_job_per_asset ON public.social_video_processing_jobs USING btree (asset_id) WHERE (status = ANY (ARRAY['pending'::text, 'processing'::text]));

CREATE INDEX idx_social_video_processing_jobs_asset ON public.social_video_processing_jobs USING btree (asset_id, created_at DESC);

CREATE INDEX idx_social_video_processing_jobs_pending ON public.social_video_processing_jobs USING btree (created_at) WHERE (status = 'pending'::text);

CREATE INDEX idx_social_week_plan_items_business ON public.social_week_plan_items USING btree (business_id, created_at DESC);

CREATE INDEX idx_social_week_plan_items_generation_queue ON public.social_week_plan_items USING btree (generation_status, created_at) WHERE (generation_status = ANY (ARRAY['queued'::text, 'generating'::text]));

CREATE UNIQUE INDEX idx_social_week_plan_items_one_generating_per_plan ON public.social_week_plan_items USING btree (plan_id) WHERE (generation_status = 'generating'::text);

CREATE INDEX idx_social_week_plan_items_plan ON public.social_week_plan_items USING btree (plan_id, sort_order);

CREATE INDEX idx_social_week_plan_items_review ON public.social_week_plan_items USING btree (plan_id, review_status);

CREATE INDEX idx_social_week_plans_business ON public.social_week_plans USING btree (business_id, week_start_date DESC);

CREATE INDEX idx_social_week_plans_business_status ON public.social_week_plans USING btree (business_id, status, created_at DESC);

CREATE INDEX idx_social_week_plans_generation_active ON public.social_week_plans USING btree (generation_status) WHERE (generation_status = ANY (ARRAY['queued'::text, 'generating'::text]));

CREATE UNIQUE INDEX idx_social_week_plans_one_active_per_week ON public.social_week_plans USING btree (business_id, week_start_date) WHERE (status <> 'archived'::text);

CREATE INDEX jobs_business_customer_idx ON public.jobs USING btree (business_id, customer_id);

CREATE INDEX jobs_business_id_stage_idx ON public.jobs USING btree (business_id, stage);

CREATE INDEX jobs_created_at_idx ON public.jobs USING btree (created_at);

CREATE INDEX jobs_google_calendar_event_idx ON public.jobs USING btree (google_calendar_event_id) WHERE (google_calendar_event_id IS NOT NULL);

CREATE INDEX jobs_scheduled_date_idx ON public.jobs USING btree (scheduled_date, business_id) WHERE (scheduled_date IS NOT NULL);

CREATE INDEX jobs_scheduled_start_idx ON public.jobs USING btree (scheduled_start, business_id) WHERE (scheduled_start IS NOT NULL);

CREATE INDEX jobs_stage_idx ON public.jobs USING btree (stage);

CREATE INDEX meta_connect_pending_sessions_expires_at_idx ON public.meta_connect_pending_sessions USING btree (expires_at);

CREATE UNIQUE INDEX notifications_business_type_reference_unique ON public.notifications USING btree (business_id, type, reference_id) WHERE (reference_id IS NOT NULL);

CREATE INDEX users_business_id_idx ON public.users USING btree (business_id);

CREATE INDEX webhook_logs_business_idx ON public.webhook_logs USING btree (business_id);

CREATE INDEX webhook_logs_created_idx ON public.webhook_logs USING btree (created_at DESC);

CREATE TRIGGER trg_social_posts_updated_at BEFORE UPDATE ON public.social_posts FOR EACH ROW EXECUTE FUNCTION public.update_social_posts_updated_at();

CREATE TRIGGER trg_social_week_plan_items_updated_at BEFORE UPDATE ON public.social_week_plan_items FOR EACH ROW EXECUTE FUNCTION public.update_social_week_plan_items_updated_at();

CREATE TRIGGER trg_social_week_plans_updated_at BEFORE UPDATE ON public.social_week_plans FOR EACH ROW EXECUTE FUNCTION public.update_social_week_plans_updated_at();

CREATE TRIGGER update_businesses_updated_at BEFORE UPDATE ON public.businesses FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER update_jobs_updated_at BEFORE UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE ONLY public.ai_usage_events
    ADD CONSTRAINT ai_usage_events_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id);

ALTER TABLE ONLY public.ai_usage_events
    ADD CONSTRAINT ai_usage_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.business_brand_assets
    ADD CONSTRAINT business_brand_assets_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.google_business_performance_daily
    ADD CONSTRAINT google_business_performance_daily_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.google_business_search_keywords
    ADD CONSTRAINT google_business_search_keywords_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.hybrid_social_renders
    ADD CONSTRAINT hybrid_social_renders_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.hybrid_social_renders
    ADD CONSTRAINT hybrid_social_renders_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.job_photos
    ADD CONSTRAINT job_photos_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.job_photos
    ADD CONSTRAINT job_photos_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.job_photos
    ADD CONSTRAINT job_photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.meta_connect_pending_sessions
    ADD CONSTRAINT meta_connect_pending_sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.render_credit_events
    ADD CONSTRAINT render_credit_events_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.render_credits
    ADD CONSTRAINT render_credits_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_credit_events
    ADD CONSTRAINT social_credit_events_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_credit_events
    ADD CONSTRAINT social_credit_events_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.social_media_assets
    ADD CONSTRAINT social_media_assets_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_media_assets
    ADD CONSTRAINT social_media_assets_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.social_posts
    ADD CONSTRAINT social_posts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_posts
    ADD CONSTRAINT social_posts_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.social_posts
    ADD CONSTRAINT social_posts_week_plan_item_id_fkey FOREIGN KEY (week_plan_item_id) REFERENCES public.social_week_plan_items(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.social_video_processing_jobs
    ADD CONSTRAINT social_video_processing_jobs_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.social_media_assets(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_video_processing_jobs
    ADD CONSTRAINT social_video_processing_jobs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_week_plan_items
    ADD CONSTRAINT social_week_plan_items_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_week_plan_items
    ADD CONSTRAINT social_week_plan_items_hybrid_render_id_fkey FOREIGN KEY (hybrid_render_id) REFERENCES public.hybrid_social_renders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.social_week_plan_items
    ADD CONSTRAINT social_week_plan_items_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.social_week_plan_items
    ADD CONSTRAINT social_week_plan_items_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.social_week_plans(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_week_plan_items
    ADD CONSTRAINT social_week_plan_items_scheduled_social_post_id_fkey FOREIGN KEY (scheduled_social_post_id) REFERENCES public.social_posts(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.social_week_plans
    ADD CONSTRAINT social_week_plans_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.social_week_plans
    ADD CONSTRAINT social_week_plans_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.social_week_plans
    ADD CONSTRAINT social_week_plans_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.webhook_logs
    ADD CONSTRAINT webhook_logs_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE SET NULL;

ALTER TABLE public.ai_image_scene_options ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.ai_usage_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.business_brand_assets ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.google_business_performance_daily ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.google_business_search_keywords ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.hybrid_social_renders ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.job_photos ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.meta_connect_pending_sessions ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.render_credit_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.render_credits ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.social_credit_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.social_media_assets ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.social_posts ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.social_style_templates ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.social_video_processing_jobs ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.social_week_plan_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.social_week_plans ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;

-- RPCs (service role only)

CREATE OR REPLACE FUNCTION public.claim_next_social_week_plan_item()
 RETURNS SETOF social_week_plan_items
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  candidate_id uuid;
  claimed social_week_plan_items;
  now_ts timestamptz := now();
BEGIN
  SELECT i.id INTO candidate_id
  FROM social_week_plan_items i
  WHERE i.generation_status = 'queued'
    AND NOT EXISTS (
      SELECT 1
      FROM social_week_plan_items g
      WHERE g.plan_id = i.plan_id
        AND g.generation_status = 'generating'
    )
  ORDER BY i.created_at ASC
  LIMIT 1
  FOR UPDATE SKIP LOCKED;

  IF candidate_id IS NULL THEN
    RETURN;
  END IF;

  UPDATE social_week_plan_items
  SET
    generation_status = 'generating',
    generation_started_at = now_ts,
    generation_error = NULL,
    updated_at = now_ts
  WHERE id = candidate_id
    AND generation_status = 'queued'
  RETURNING * INTO claimed;

  IF claimed.id IS NULL THEN
    RETURN;
  END IF;

  UPDATE social_week_plans
  SET
    generation_status = 'generating',
    updated_at = now_ts
  WHERE id = claimed.plan_id
    AND business_id = claimed.business_id
    AND generation_status IN ('queued', 'generating');

  RETURN NEXT claimed;
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.claim_next_social_week_plan_item() FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.claim_next_social_week_plan_item() TO service_role;

