'use client'

import {
  QUOTE_CTA_LINE_MAX,
  QUOTE_CUSTOMER_NAME_MAX,
  QUOTE_INTRO_LINE_MAX,
  QUOTE_TEXT_MAX,
} from '@/lib/social/quoteCardContent'

export type QuoteCardFormContent = {
  quoteText: string
  customerName: string
  starRating?: number
  introLine: string
  ctaLine: string
}

export function QuoteCardContentFields({
  content,
  onChange,
}: {
  content: QuoteCardFormContent
  onChange: (next: QuoteCardFormContent) => void
}) {
  return (
    <div className="space-y-3">
      <p className="text-xs text-[#666]">
        Enter the customer&apos;s words yourself - quotes are never generated by AI.
      </p>
      <div>
        <label className="mb-1 block text-xs font-semibold text-[#666]">
          Quote <span className="text-red-500">*</span>
        </label>
        <textarea
          value={content.quoteText}
          maxLength={QUOTE_TEXT_MAX}
          rows={4}
          onChange={(e) => onChange({ ...content, quoteText: e.target.value })}
          className="w-full rounded-lg border border-[#E0DDD5] px-3 py-2 text-sm resize-y min-h-[88px]"
          placeholder="Paste the customer's review or testimonial here"
        />
        <p className="mt-0.5 text-[10px] text-[#AAA]">{content.quoteText.length}/{QUOTE_TEXT_MAX}</p>
      </div>
      <div>
        <label className="mb-1 block text-xs font-semibold text-[#666]">
          Customer name <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          value={content.customerName}
          maxLength={QUOTE_CUSTOMER_NAME_MAX}
          onChange={(e) => onChange({ ...content, customerName: e.target.value })}
          className="w-full rounded-lg border border-[#E0DDD5] px-3 py-2 text-sm"
          placeholder="e.g. Sarah M."
        />
      </div>
      <div>
        <label className="mb-1.5 block text-xs font-semibold text-[#666]">Star rating (optional)</label>
        <div className="flex flex-wrap gap-1.5">
          {[1, 2, 3, 4, 5].map((n) => (
            <button
              key={n}
              type="button"
              onClick={() =>
                onChange({
                  ...content,
                  starRating: content.starRating === n ? undefined : n,
                })
              }
              className={`rounded-lg px-2.5 py-1.5 text-[11px] font-semibold transition-colors ${
                content.starRating === n
                  ? 'bg-[#FFD700] text-black'
                  : 'border border-[#E0DDD5] bg-white text-[#555] hover:border-[#CCC]'
              }`}
            >
              {n} ★
            </button>
          ))}
        </div>
      </div>
      <div>
        <label className="mb-1 block text-xs font-semibold text-[#666]">Intro line (optional)</label>
        <input
          type="text"
          value={content.introLine}
          maxLength={QUOTE_INTRO_LINE_MAX}
          onChange={(e) => onChange({ ...content, introLine: e.target.value })}
          className="w-full rounded-lg border border-[#E0DDD5] px-3 py-2 text-sm"
          placeholder="What our customers say"
        />
      </div>
      <div>
        <label className="mb-1 block text-xs font-semibold text-[#666]">CTA line (optional)</label>
        <input
          type="text"
          value={content.ctaLine}
          maxLength={QUOTE_CTA_LINE_MAX}
          onChange={(e) => onChange({ ...content, ctaLine: e.target.value })}
          className="w-full rounded-lg border border-[#E0DDD5] px-3 py-2 text-sm"
          placeholder="Call us for a free quote"
        />
      </div>
    </div>
  )
}
