/** Explicit allowlist for social_posts - used by /api/social/context (no SELECT *). */
export const SOCIAL_POSTS_SELECT = [
  'id',
  'status',
  'publishing_mode',
  'caption',
  'platforms',
  'photo_urls',
  'processed_photo_urls',
  'scheduled_for',
  'posted_at',
  'posted_manually',
  'job_suburb',
  'job_state',
  'trade_type',
  'facebook_post_id',
  'instagram_post_id',
  'gmb_post_id',
  'facebook_error',
  'instagram_error',
  'gmb_error',
  'tiktok_post_id',
  'tiktok_error',
  'tiktok_status',
  'created_at',
].join(', ')
