/** TradiesPost static asset paths (WebP). */

export const TP_ASSETS = {
  logoHorizontal: '/tradiespost/logo-horizontal.webp',
  hero: '/tradiespost/hero.webp',
  createPhotosVideos: '/tradiespost/create-photos-videos.webp',
  createYourIdea: '/tradiespost/create-your-idea.webp',
  createSomethingYouLike: '/tradiespost/create-something-you-like.webp',
  createIconPhotos: '/tradiespost/create-icon-1.webp',
  createIconIdea: '/tradiespost/create-icon-2.webp',
  createIconHeart: '/tradiespost/create-icon-3.webp',
  howAddContent: '/tradiespost/how-add-content.webp',
  howBuddyBuilds: '/tradiespost/how-buddy-builds-transparent.webp',
  howBuddyLaptop: '/tradiespost/how-buddy-builds.webp',
  howApprovePost: '/tradiespost/how-approve-post.webp',
  howScheduleGo: '/tradiespost/how-schedule-go.webp',
  agencyDevices: '/tradiespost/agency-devices.webp',
  soWeBuiltDevices: '/tradiespost/so-we-built-devices.webp',
  agencyIconDesigns: '/tradiespost/agency-icon-designs.webp',
  agencyIconCaptions: '/tradiespost/agency-icon-captions.webp',
  agencyIconBrand: '/tradiespost/agency-icon-brand.webp',
  agencyIconBusy: '/tradiespost/agency-icon-busy.webp',
  agencyIconDevices: '/tradiespost/agency-icon-devices.webp',
  personasPhoto: '/tradiespost/personas-photo.webp',
  personasJustRealResults: '/tradiespost/personas-just-real-results.webp',
  lessAdminMoreWork: '/tradiespost/less-admin-more-work.webp',
  planMostTradiesChoose: '/tradiespost/plan-most-tradies-choose.webp',
  moreVisibilityMoreWork: '/tradiespost/more-visibility-more-work.webp',
  mattC: '/tradiespost/matt-c.webp',
  pricingBuddy: '/tradiespost/pricing-buddy.webp',
  logoWidth: 1024,
  logoHeight: 341,
  heroWidth: 1024,
  heroHeight: 576,
  createPhotosVideosWidth: 819,
  createPhotosVideosHeight: 1024,
  createYourIdeaWidth: 859,
  createYourIdeaHeight: 1024,
  createSomethingYouLikeWidth: 819,
  createSomethingYouLikeHeight: 1024,
  createIconSize: 48,
  howAddContentWidth: 1024,
  howAddContentHeight: 768,
  howBuddyBuildsWidth: 771,
  howBuddyBuildsHeight: 864,
  howBuddyLaptopWidth: 1024,
  howBuddyLaptopHeight: 1024,
  howApprovePostWidth: 825,
  howApprovePostHeight: 953,
  howScheduleGoWidth: 1024,
  howScheduleGoHeight: 768,
  agencyDevicesWidth: 1024,
  agencyDevicesHeight: 454,
  soWeBuiltDevicesWidth: 1012,
  soWeBuiltDevicesHeight: 606,
  agencyIconSize: 128,
  personasPhotoWidth: 1024,
  personasPhotoHeight: 643,
  personasJustRealResultsWidth: 1004,
  personasJustRealResultsHeight: 323,
  lessAdminMoreWorkWidth: 942,
  lessAdminMoreWorkHeight: 859,
  planMostTradiesChooseWidth: 628,
  planMostTradiesChooseHeight: 679,
  moreVisibilityMoreWorkWidth: 640,
  moreVisibilityMoreWorkHeight: 828,
  mattCWidth: 738,
  mattCHeight: 612,
  pricingBuddyWidth: 440,
  pricingBuddyHeight: 440,
} as const

export const TP_AGENCY_QUALITY_FEATURES = [
  {
    title: 'Professional designs',
    body: 'Agency-level quality without the cost.',
    icon: TP_ASSETS.agencyIconDesigns,
  },
  {
    title: 'Captions included',
    body: 'Written for your business. Ready to post.',
    icon: TP_ASSETS.agencyIconCaptions,
  },
  {
    title: 'Your brand, every time',
    body: 'Consistent fonts, colours and look across every post.',
    icon: TP_ASSETS.agencyIconBrand,
  },
  {
    title: 'Built for busy people',
    body: 'Done in minutes, not hours.',
    icon: TP_ASSETS.agencyIconBusy,
  },
  {
    title: 'Works on any device',
    body: 'Desktop, tablet or mobile.',
    icon: TP_ASSETS.agencyIconDevices,
  },
] as const

export const TP_CREATE_IT_COLUMNS = [
  {
    icon: TP_ASSETS.createIconPhotos,
    iconWidth: TP_ASSETS.createIconSize,
    iconHeight: TP_ASSETS.createIconSize,
    title: 'Your photos & videos',
    body: 'Use your products, pre-orders, reviews, behind-the-scenes and more.',
    image: TP_ASSETS.createPhotosVideos,
    width: TP_ASSETS.createPhotosVideosWidth,
    height: TP_ASSETS.createPhotosVideosHeight,
    alt: 'Stack of branded posts created from product photos',
  },
  {
    icon: TP_ASSETS.createIconIdea,
    iconWidth: TP_ASSETS.createIconSize,
    iconHeight: TP_ASSETS.createIconSize,
    title: 'Your idea',
    body: 'Tell us what you want to promote and we’ll create it for you.',
    image: TP_ASSETS.createYourIdea,
    width: TP_ASSETS.createYourIdeaWidth,
    height: TP_ASSETS.createYourIdeaHeight,
    alt: 'Promote a bathroom renovation service - AI-generated branded post preview',
  },
  {
    icon: TP_ASSETS.createIconHeart,
    iconWidth: TP_ASSETS.createIconSize,
    iconHeight: TP_ASSETS.createIconSize,
    title: 'Something you like',
    body: 'Upload a post you like and we’ll take inspiration and make it original for your business.',
    image: TP_ASSETS.createSomethingYouLike,
    width: TP_ASSETS.createSomethingYouLikeWidth,
    height: TP_ASSETS.createSomethingYouLikeHeight,
    alt: 'Turn inspiration post into an original branded roofing graphic',
  },
] as const

export const TP_CREATE_ROUTE_CARDS = [
  {
    title: TP_CREATE_IT_COLUMNS[0].title,
    body: TP_CREATE_IT_COLUMNS[0].body,
    image: TP_CREATE_IT_COLUMNS[0].image,
    width: TP_CREATE_IT_COLUMNS[0].width,
    height: TP_CREATE_IT_COLUMNS[0].height,
    alt: TP_CREATE_IT_COLUMNS[0].alt,
  },
  {
    title: TP_CREATE_IT_COLUMNS[1].title,
    body: TP_CREATE_IT_COLUMNS[1].body,
    image: TP_CREATE_IT_COLUMNS[1].image,
    width: TP_CREATE_IT_COLUMNS[1].width,
    height: TP_CREATE_IT_COLUMNS[1].height,
    alt: TP_CREATE_IT_COLUMNS[1].alt,
  },
  {
    title: TP_CREATE_IT_COLUMNS[2].title,
    body: TP_CREATE_IT_COLUMNS[2].body,
    image: TP_CREATE_IT_COLUMNS[2].image,
    width: TP_CREATE_IT_COLUMNS[2].width,
    height: TP_CREATE_IT_COLUMNS[2].height,
    alt: TP_CREATE_IT_COLUMNS[2].alt,
  },
] as const

export const TP_HOW_IT_WORKS_STEPS = [
  {
    step: '1',
    title: 'Add your content or idea',
    body: 'Upload photos, videos, reviews or tell us what you want to promote.',
    image: TP_ASSETS.howAddContent,
    width: TP_ASSETS.howAddContentWidth,
    height: TP_ASSETS.howAddContentHeight,
    alt: 'Upload photos, videos, reviews or ideas into TradiesPost',
  },
  {
    step: '2',
    title: 'Buddy builds your month',
    body: 'We create the designs, captions and content mix you need.',
    image: TP_ASSETS.howBuddyLaptop,
    width: TP_ASSETS.howBuddyLaptopWidth,
    height: TP_ASSETS.howBuddyLaptopHeight,
    alt: 'Illustration of social content being built on a laptop',
  },
  {
    step: '3',
    title: 'You pick & approve',
    body: 'Choose your favourites, make small tweaks and approve.',
    image: TP_ASSETS.howApprovePost,
    width: TP_ASSETS.howApprovePostWidth,
    height: TP_ASSETS.howApprovePostHeight,
    alt: 'Approved branded decking post ready to schedule',
    showApprovedBadge: true,
  },
  {
    step: '4',
    title: 'Schedule & go',
    body: 'Use the calendar or connect Facebook & Instagram to auto-post.',
    image: TP_ASSETS.howScheduleGo,
    width: TP_ASSETS.howScheduleGoWidth,
    height: TP_ASSETS.howScheduleGoHeight,
    alt: 'Calendar with scheduled posts and social connections',
  },
] as const

export const TP_PERSONAS_CARDS = [
  {
    icon: 'user' as const,
    title: 'Do it yourself',
    body: 'Get it done fast and stay in control.',
  },
  {
    icon: 'settings' as const,
    title: 'Give it to your admin',
    body: 'If they know the business, they can run it.',
  },
  {
    icon: 'crosshair' as const,
    title: 'Give it to your VA',
    body: 'Create, approve and schedule with ease.',
  },
] as const

export const TP_PERSONAS_CHECKS = [
  'No design skills',
  'No copywriting skills',
  'No marketing degree',
] as const
