import type { BlueprintLayout } from "./layout-types";
import type { WebsiteBlueprintId } from "./types";

export const BLUEPRINT_LAYOUTS: Record<WebsiteBlueprintId, BlueprintLayout> = {
  editorial: {
    header: "CENTRED",
    hero: "EDITORIAL_STACK",
    merch: "FEATURE_ROWS_LARGE_GRID",
    gridColumns: { desktop: 3, mobile: 1 },
    cardTreatment: "BORDERLESS",
    imageShape: "RECT",
    sectionSpacing: "XL",
    colourMode: "WARM",
  },
  marketplace: {
    header: "CLASSIC",
    hero: "SPLIT_CATEGORY_TILES",
    merch: "CATEGORY_ROWS",
    gridColumns: { desktop: "SCROLL_ROW", mobile: "SCROLL_ROW" },
    cardTreatment: "TINTED",
    imageShape: "ROUNDED",
    sectionSpacing: "M",
    colourMode: "LIGHT",
  },
  heritage: {
    header: "STACKED",
    hero: "ARCH_FRAME",
    merch: "STORY_COLUMNS_MENU_LIST",
    gridColumns: { desktop: "LIST", mobile: "LIST" },
    cardTreatment: "LIST_ROW",
    imageShape: "ARCH",
    sectionSpacing: "L",
    colourMode: "TINTED",
  },
  minimal: {
    header: "MINIMAL_ICON",
    hero: "FRAMED_INSET",
    merch: "LARGE_GRID_2",
    gridColumns: { desktop: 2, mobile: 1 },
    cardTreatment: "BORDERLESS",
    imageShape: "RECT",
    sectionSpacing: "XXL",
    colourMode: "LIGHT",
  },
  bold: {
    header: "BOLD_BAR",
    hero: "TYPE_BLOCK",
    merch: "COLOUR_BLOCKS_GRID_4",
    gridColumns: { desktop: 4, mobile: 2 },
    cardTreatment: "THICK_BORDER",
    imageShape: "CUTOUT",
    sectionSpacing: "S",
    colourMode: "DARK",
  },
  local: {
    header: "INFO_BAR",
    hero: "FULL_BLEED",
    merch: "AVAILABLE_NOW",
    gridColumns: { desktop: 3, mobile: 2 },
    cardTreatment: "SOFT_SHADOW",
    imageShape: "ROUNDED",
    sectionSpacing: "M",
    colourMode: "WARM",
  },
  studio: {
    header: "MINIMAL_ICON",
    hero: "COLLAGE_TRIO",
    merch: "GALLERY_PROCESS",
    gridColumns: { desktop: "MASONRY", mobile: "MASONRY" },
    cardTreatment: "CAPTIONED",
    imageShape: "MIXED_RATIO",
    sectionSpacing: "L",
    colourMode: "STONE",
  },
  "modern-store": {
    header: "CLASSIC",
    hero: "SPLIT_MEDIA",
    merch: "TABBED_GRID_4",
    gridColumns: { desktop: 4, mobile: 2 },
    cardTreatment: "HAIRLINE",
    imageShape: "ROUNDED",
    sectionSpacing: "M",
    colourMode: "LIGHT",
  },
  catalogue: {
    header: "UTILITY_SEARCH",
    hero: "PROMO_BANNER",
    merch: "DENSE_GRID_6",
    gridColumns: { desktop: 6, mobile: 2 },
    cardTreatment: "COMPACT_HAIRLINE",
    imageShape: "RECT",
    sectionSpacing: "S",
    colourMode: "LIGHT",
  },
  boutique: {
    header: "CENTRED",
    hero: "PRODUCT_FEATURE",
    merch: "CURATED_SETS",
    gridColumns: { desktop: 3, mobile: 2 },
    cardTreatment: "TINTED_PANEL",
    imageShape: "ROUNDED_LG",
    sectionSpacing: "L",
    colourMode: "BLUSH",
  },
};
