import type { WebsiteBlueprint, WebsiteBlueprintId } from "./types";
import { WEBSITE_BLUEPRINT_IDS, isWebsiteBlueprintId } from "./types";

const BLUEPRINTS: Record<WebsiteBlueprintId, WebsiteBlueprint> = {
  editorial: {
    id: "editorial",
    name: "Editorial",
    description: "Image-led and spacious, with strong storytelling and a premium product focus.",
    designSystem: "artisan",
    traits: ["image-led", "spacious", "premium", "story-forward"],
    suitableFor: ["fashion", "artisan", "premium food", "homewares"],
    layoutRecipe: "story_led",
    preferredHomeSlots: ["story", "commerce", "trust", "pickup", "signup"],
    preferredPresets: { Hero: "editorial", ProductGrid: "editorial", ImageText: "editorial" },
    contentDensity: "low",
    imageEmphasis: "high",
    commerceEmphasis: "balanced",
    previewTone: {
      bg: "#faf8f5",
      ink: "#1c1917",
      muted: "#78716c",
      accent: "#44403c",
      wash: "#f5f0e8",
      heroStyle: "split",
      productCols: 2,
      cardRadius: "0.25rem",
    },
  },
  marketplace: {
    id: "marketplace",
    name: "Marketplace",
    description: "Category-rich and discovery-focused — practical shopping with clear navigation.",
    designSystem: "market",
    traits: ["discovery", "practical", "category-led", "commercial"],
    suitableFor: ["multi-category", "retail", "farm shops", "pet"],
    layoutRecipe: "browse_catalog",
    preferredHomeSlots: ["categories", "commerce", "trust", "story", "signup"],
    preferredPresets: { Hero: "shop-first", ProductGrid: "classic", CategoryGrid: "tiles" },
    contentDensity: "high",
    imageEmphasis: "medium",
    commerceEmphasis: "commerce-led",
    previewTone: {
      bg: "#ffffff",
      ink: "#0f172a",
      muted: "#64748b",
      accent: "#0f766e",
      wash: "#f1f5f9",
      heroStyle: "full",
      productCols: 3,
      cardRadius: "0.75rem",
    },
  },
  heritage: {
    id: "heritage",
    name: "Heritage",
    description: "Warm and established — story-led craft without feeling outdated.",
    designSystem: "farmhouse",
    traits: ["warm", "story-led", "crafted", "traditional"],
    suitableFor: ["farms", "makers", "handmade", "local brands"],
    layoutRecipe: "story_led",
    preferredHomeSlots: ["story", "commerce", "farm_stand", "trust", "signup"],
    preferredPresets: { Hero: "split", ProductGrid: "farm-grid", About: "card" },
    contentDensity: "medium",
    imageEmphasis: "medium",
    commerceEmphasis: "story-led",
    previewTone: {
      bg: "#f7f3eb",
      ink: "#3f2a1d",
      muted: "#8b7355",
      accent: "#6b4f3a",
      wash: "#efe6d6",
      heroStyle: "split",
      productCols: 3,
      cardRadius: "0.5rem",
    },
  },
  minimal: {
    id: "minimal",
    name: "Minimal",
    description: "Clean whitespace with product photography front and centre.",
    designSystem: "artisan",
    traits: ["clean", "restrained", "whitespace", "photo-led"],
    suitableFor: ["jewellery", "skincare", "beauty", "design"],
    layoutRecipe: "shop_first",
    preferredHomeSlots: ["commerce", "story", "trust", "signup"],
    preferredPresets: { Hero: "minimal", ProductGrid: "editorial" },
    contentDensity: "low",
    imageEmphasis: "high",
    commerceEmphasis: "balanced",
    previewTone: {
      bg: "#ffffff",
      ink: "#171717",
      muted: "#a3a3a3",
      accent: "#171717",
      wash: "#fafafa",
      heroStyle: "minimal",
      productCols: 2,
      cardRadius: "0",
    },
  },
  bold: {
    id: "bold",
    name: "Bold",
    description: "High-impact type and punchy blocks for energetic modern brands.",
    designSystem: "market",
    traits: ["energetic", "high-impact", "punchy", "modern"],
    suitableFor: ["streetwear", "merch", "DTC", "colourful products"],
    layoutRecipe: "shop_first",
    preferredHomeSlots: ["commerce", "categories", "how_it_works", "trust", "signup"],
    preferredPresets: { Hero: "promo", ProductGrid: "featured", Text: "centre" },
    contentDensity: "medium",
    imageEmphasis: "high",
    commerceEmphasis: "commerce-led",
    previewTone: {
      bg: "#0a0a0a",
      ink: "#fafafa",
      muted: "#a3a3a3",
      accent: "#f97316",
      wash: "#171717",
      heroStyle: "bold",
      productCols: 2,
      cardRadius: "1rem",
    },
  },
  local: {
    id: "local",
    name: "Local",
    description: "Approachable and location-first — visit, pickup, and what’s available.",
    designSystem: "farmhouse",
    traits: ["community", "practical", "location-first", "friendly"],
    suitableFor: ["farm stands", "florists", "market sellers", "local producers"],
    layoutRecipe: "local_visit",
    preferredHomeSlots: ["farm_stand", "commerce", "pickup", "story", "signup"],
    preferredPresets: { Hero: "farm-landscape", FarmStand: "visit", Pickup: "cards" },
    contentDensity: "medium",
    imageEmphasis: "medium",
    commerceEmphasis: "balanced",
    previewTone: {
      bg: "#f4f7f0",
      ink: "#1a2e1a",
      muted: "#5c735c",
      accent: "#3d6b3d",
      wash: "#e8f0e4",
      heroStyle: "full",
      productCols: 3,
      cardRadius: "0.75rem",
    },
  },
  studio: {
    id: "studio",
    name: "Studio",
    description: "Maker-led visual storytelling with a gallery feel.",
    designSystem: "artisan",
    traits: ["maker-led", "gallery", "personal", "process"],
    suitableFor: ["ceramics", "artists", "custom", "limited runs"],
    layoutRecipe: "story_led",
    preferredHomeSlots: ["story", "commerce", "how_it_works", "trust", "signup"],
    preferredPresets: { Hero: "editorial", ImageText: "editorial", ProductGrid: "featured" },
    contentDensity: "low",
    imageEmphasis: "high",
    commerceEmphasis: "story-led",
    previewTone: {
      bg: "#f8f6f3",
      ink: "#292524",
      muted: "#78716c",
      accent: "#57534e",
      wash: "#efece7",
      heroStyle: "collage",
      productCols: 2,
      cardRadius: "0.25rem",
    },
  },
  "modern-store": {
    id: "modern-store",
    name: "Modern Store",
    description: "Polished contemporary ecommerce — balanced brand and shopping.",
    designSystem: "market",
    traits: ["polished", "versatile", "balanced", "contemporary"],
    suitableFor: ["general ecommerce", "growing brands", "multi-category"],
    layoutRecipe: "shop_first",
    preferredHomeSlots: ["commerce", "categories", "story", "trust", "signup"],
    preferredPresets: { Hero: "shop-first", ProductGrid: "classic", CategoryGrid: "cards" },
    contentDensity: "medium",
    imageEmphasis: "medium",
    commerceEmphasis: "balanced",
    previewTone: {
      bg: "#ffffff",
      ink: "#18181b",
      muted: "#71717a",
      accent: "#2563eb",
      wash: "#f4f4f5",
      heroStyle: "split",
      productCols: 3,
      cardRadius: "0.5rem",
    },
  },
  catalogue: {
    id: "catalogue",
    name: "Catalogue",
    description: "Dense and efficient — built for larger ranges and fast discovery.",
    designSystem: "market",
    traits: ["dense", "category-rich", "commerce-first", "efficient"],
    suitableFor: ["large SKU", "apparel", "specialty retail", "equestrian"],
    layoutRecipe: "browse_catalog",
    preferredHomeSlots: ["categories", "commerce", "trust", "story", "signup"],
    preferredPresets: { Hero: "product-collage", ProductGrid: "compact", CategoryGrid: "compact" },
    contentDensity: "high",
    imageEmphasis: "medium",
    commerceEmphasis: "commerce-led",
    previewTone: {
      bg: "#ffffff",
      ink: "#111827",
      muted: "#6b7280",
      accent: "#111827",
      wash: "#f9fafb",
      heroStyle: "collage",
      productCols: 4,
      cardRadius: "0.375rem",
    },
  },
  boutique: {
    id: "boutique",
    name: "Boutique",
    description: "Premium and curated — warm refinement without stark minimalism.",
    designSystem: "artisan",
    traits: ["premium", "curated", "warm", "refined"],
    suitableFor: ["gifts", "candles", "skincare", "specialty food"],
    layoutRecipe: "story_led",
    preferredHomeSlots: ["commerce", "story", "trust", "signup"],
    preferredPresets: { Hero: "editorial", ProductGrid: "featured", ImageText: "image-left" },
    contentDensity: "low",
    imageEmphasis: "high",
    commerceEmphasis: "balanced",
    previewTone: {
      bg: "#faf7f5",
      ink: "#3b2f2f",
      muted: "#9a8b8b",
      accent: "#8b5e5e",
      wash: "#f3ebe8",
      heroStyle: "split",
      productCols: 2,
      cardRadius: "0.75rem",
    },
  },
};

export function listWebsiteBlueprints(): WebsiteBlueprint[] {
  return WEBSITE_BLUEPRINT_IDS.map((id) => BLUEPRINTS[id]);
}

export function getWebsiteBlueprint(id: WebsiteBlueprintId): WebsiteBlueprint {
  return BLUEPRINTS[id];
}

export function resolveWebsiteBlueprint(
  id: string | null | undefined,
): WebsiteBlueprint | null {
  if (!id || !isWebsiteBlueprintId(id)) return null;
  return BLUEPRINTS[id];
}

export { WEBSITE_BLUEPRINT_IDS, isWebsiteBlueprintId };
