-- AlterTable
ALTER TABLE "Stand" ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT;
ALTER TABLE "Stand" ADD COLUMN IF NOT EXISTS "facebookUrl" TEXT;
ALTER TABLE "Stand" ADD COLUMN IF NOT EXISTS "tiktokUrl" TEXT;
ALTER TABLE "Stand" ADD COLUMN IF NOT EXISTS "youtubeUrl" TEXT;
ALTER TABLE "Stand" ADD COLUMN IF NOT EXISTS "websiteUrl" TEXT;
